/* sdx.c generated by valac 0.34.8, the Vala compiler
 * generated from sdx.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_pixels.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_events.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_hints.h>
#include <SDL_ttf.h>
#include <SDL2/SDL_timer.h>
#include "mt19937ar.h"
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL_keyboard.h>


#define SDX_TYPE_FONT (sdx_font_get_type ())
#define SDX_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_FONT, sdxFont))
#define SDX_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_FONT, sdxFontClass))
#define SDX_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_FONT))
#define SDX_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_FONT))
#define SDX_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_FONT, sdxFontClass))

typedef struct _sdxFont sdxFont;
typedef struct _sdxFontClass sdxFontClass;

#define SDX_GRAPHICS_TYPE_SPRITE (sdx_graphics_sprite_get_type ())
#define SDX_GRAPHICS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSprite))
#define SDX_GRAPHICS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))
#define SDX_GRAPHICS_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))

typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _sdxgraphicsSpriteClass sdxgraphicsSpriteClass;
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))
#define _SDL_DestroyRenderer0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyRenderer (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _sdxgraphicsSpritePrivate sdxgraphicsSpritePrivate;

#define SDX_GRAPHICS_TYPE_SCALE (sdx_graphics_scale_get_type ())
typedef struct _sdxgraphicsScale sdxgraphicsScale;

typedef enum  {
	SDX_SDL_EXCEPTION_Initialization,
	SDX_SDL_EXCEPTION_ImageInitialization,
	SDX_SDL_EXCEPTION_TtfInitialization,
	SDX_SDL_EXCEPTION_TextureFilteringNotEnabled,
	SDX_SDL_EXCEPTION_OpenWindow,
	SDX_SDL_EXCEPTION_CreateRenderer
} sdxSdlException;
#define SDX_SDL_EXCEPTION sdx_sdl_exception_quark ()
struct _sdxgraphicsScale {
	gdouble x;
	gdouble y;
};

struct _sdxgraphicsSprite {
	GObject parent_instance;
	sdxgraphicsSpritePrivate * priv;
	SDL_Texture* texture;
	SDL_Surface* surface;
	gint width;
	gint height;
	gint x;
	gint y;
	sdxgraphicsScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gint id;
	gchar* path;
	gboolean isText;
};

struct _sdxgraphicsSpriteClass {
	GObjectClass parent_class;
};


extern SDL_Renderer* sdx_renderer;
SDL_Renderer* sdx_renderer = NULL;
extern sdxFont* sdx_font;
sdxFont* sdx_font = NULL;
extern sdxFont* sdx_smallFont;
sdxFont* sdx_smallFont = NULL;
extern sdxFont* sdx_largeFont;
sdxFont* sdx_largeFont = NULL;
extern sdxgraphicsSprite* sdx_fpsSprite;
sdxgraphicsSprite* sdx_fpsSprite = NULL;
extern SDL_Color sdx_fpsColor;
SDL_Color sdx_fpsColor = {0};
extern gboolean sdx_showFps;
gboolean sdx_showFps = FALSE;
extern gdouble sdx_fps;
gdouble sdx_fps = 0.0;
extern gdouble sdx_delta;
gdouble sdx_delta = 0.0;
extern gdouble sdx_mouseX;
gdouble sdx_mouseX = 0.0;
extern gdouble sdx_mouseY;
gdouble sdx_mouseY = 0.0;
extern gboolean sdx_mouseDown;
gboolean sdx_mouseDown = FALSE;
extern gboolean sdx_running;
gboolean sdx_running = FALSE;
extern guint8* sdx_keys;
extern gint sdx_keys_length1;
guint8* sdx_keys = NULL;
gint sdx_keys_length1 = 0;
static gint _sdx_keys_size_ = 0;
extern gint sdx__frames;
gint sdx__frames = 0;
extern SDL_Event sdx__evt;
SDL_Event sdx__evt = {0};
extern gdouble sdx__elapsed;
gdouble sdx__elapsed = 0.0;
extern gdouble sdx__freq;
gdouble sdx__freq = 0.0;
extern gdouble sdx__mark1;
gdouble sdx__mark1 = 0.0;
extern gdouble sdx__mark2;
gdouble sdx__mark2 = 0.0;

GQuark sdx_sdl_exception_quark (void);
GType sdx_font_get_type (void) G_GNUC_CONST;
GType sdx_graphics_sprite_get_type (void) G_GNUC_CONST;
SDL_Window* sdx_initialize (gint width, gint height, const gchar* name);
gdouble sdx_getRandom (void);
void sdx_setDefaultFont (const gchar* path, gint size);
sdxFont* sdx_font_new (const gchar* path, gint size);
sdxFont* sdx_font_construct (GType object_type, const gchar* path, gint size);
void sdx_setSmallFont (const gchar* path, gint size);
void sdx_setLargeFont (const gchar* path, gint size);
void sdx_setShowFps (gboolean value);
sdxgraphicsSprite* sdx_graphics_sprite_new (const gchar* path, sdxFont* font, SDL_Color* color);
sdxgraphicsSprite* sdx_graphics_sprite_construct (GType object_type, const gchar* path, sdxFont* font, SDL_Color* color);
GType sdx_graphics_scale_get_type (void) G_GNUC_CONST;
sdxgraphicsScale* sdx_graphics_scale_dup (const sdxgraphicsScale* self);
void sdx_graphics_scale_free (sdxgraphicsScale* self);
void sdx_drawFps (void);
void sdx_graphics_sprite_setText (sdxgraphicsSprite* self, const gchar* text, sdxFont* font, SDL_Color color);
void sdx_graphics_sprite_render (sdxgraphicsSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip);
gdouble sdx_getNow (void);
void sdx_start (void);
void sdx_update (void);
void sdx_processEvents (void);
void sdx_begin (void);
void sdx_end (void);

extern const SDL_Color SDX_COLOR_AntiqueWhite;

GQuark sdx_sdl_exception_quark (void) {
	return g_quark_from_static_string ("sdx_sdl_exception-quark");
}


/**
 * Initialization
 * 
 */
SDL_Window* sdx_initialize (gint width, gint height, const gchar* name) {
	SDL_Window* result = NULL;
	guint8* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp4_ = 0;
	gboolean _tmp7_ = FALSE;
	gint _tmp10_ = 0;
	SDL_Window* window = NULL;
	const gchar* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	gint _tmp15_ = 0;
	SDL_Window* _tmp16_ = NULL;
	SDL_Window* _tmp17_ = NULL;
	SDL_Window* _tmp20_ = NULL;
	SDL_Renderer* _tmp21_ = NULL;
	SDL_Renderer* _tmp22_ = NULL;
	guint64 _tmp25_ = 0ULL;
	guint64 _tmp26_ = 0ULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = g_new0 (guint8, 256);
	sdx_keys = (g_free (sdx_keys), NULL);
	sdx_keys = _tmp0_;
	sdx_keys_length1 = 256;
	_sdx_keys_size_ = sdx_keys_length1;
	_tmp1_ = SDL_Init ((guint32) ((SDL_INIT_VIDEO | SDL_INIT_TIMER) | SDL_INIT_EVENTS));
	if (_tmp1_ < 0) {
		const gchar* _tmp2_ = NULL;
		GError* _tmp3_ = NULL;
		_tmp2_ = SDL_GetError ();
		_tmp3_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_Initialization, _tmp2_);
		_inner_error_ = _tmp3_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp4_ = IMG_Init ((gint) IMG_INIT_PNG);
	if (_tmp4_ < 0) {
		const gchar* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		_tmp5_ = SDL_GetError ();
		_tmp6_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_ImageInitialization, _tmp5_);
		_inner_error_ = _tmp6_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp7_ = SDL_SetHint (SDL_HINT_RENDER_SCALE_QUALITY, "1");
	if (!_tmp7_) {
		const gchar* _tmp8_ = NULL;
		GError* _tmp9_ = NULL;
		_tmp8_ = SDL_GetError ();
		_tmp9_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_TextureFilteringNotEnabled, _tmp8_);
		_inner_error_ = _tmp9_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp10_ = TTF_Init ();
	if (_tmp10_ == -1) {
		const gchar* _tmp11_ = NULL;
		GError* _tmp12_ = NULL;
		_tmp11_ = SDL_GetError ();
		_tmp12_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_TtfInitialization, _tmp11_);
		_inner_error_ = _tmp12_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp13_ = name;
	_tmp14_ = width;
	_tmp15_ = height;
	_tmp16_ = SDL_CreateWindow (_tmp13_, (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, _tmp14_, _tmp15_, (guint32) SDL_WINDOW_SHOWN);
	window = _tmp16_;
	_tmp17_ = window;
	if (_tmp17_ == NULL) {
		const gchar* _tmp18_ = NULL;
		GError* _tmp19_ = NULL;
		_tmp18_ = SDL_GetError ();
		_tmp19_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_OpenWindow, _tmp18_);
		_inner_error_ = _tmp19_;
		_SDL_DestroyWindow0 (window);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp20_ = window;
	_tmp21_ = SDL_CreateRenderer (_tmp20_, -1, (guint32) (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC));
	_SDL_DestroyRenderer0 (sdx_renderer);
	sdx_renderer = _tmp21_;
	_tmp22_ = sdx_renderer;
	if (_tmp22_ == NULL) {
		const gchar* _tmp23_ = NULL;
		GError* _tmp24_ = NULL;
		_tmp23_ = SDL_GetError ();
		_tmp24_ = g_error_new_literal (SDX_SDL_EXCEPTION, SDX_SDL_EXCEPTION_CreateRenderer, _tmp23_);
		_inner_error_ = _tmp24_;
		_SDL_DestroyWindow0 (window);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp25_ = SDL_GetPerformanceFrequency ();
	sdx__freq = (gdouble) _tmp25_;
	sdx_fpsColor = SDX_COLOR_AntiqueWhite;
	_tmp26_ = SDL_GetPerformanceCounter ();
	init_genrand ((gulong) _tmp26_);
	result = window;
	return result;
}


gdouble sdx_getRandom (void) {
	gdouble result = 0.0;
	gdouble _tmp0_ = 0.0;
	_tmp0_ = genrand_real2 ();
	result = _tmp0_;
	return result;
}


void sdx_setDefaultFont (const gchar* path, gint size) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	sdxFont* _tmp2_ = NULL;
	g_return_if_fail (path != NULL);
	_tmp0_ = path;
	_tmp1_ = size;
	_tmp2_ = sdx_font_new (_tmp0_, _tmp1_);
	_g_object_unref0 (sdx_font);
	sdx_font = _tmp2_;
}


void sdx_setSmallFont (const gchar* path, gint size) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	sdxFont* _tmp2_ = NULL;
	g_return_if_fail (path != NULL);
	_tmp0_ = path;
	_tmp1_ = size;
	_tmp2_ = sdx_font_new (_tmp0_, _tmp1_);
	_g_object_unref0 (sdx_smallFont);
	sdx_smallFont = _tmp2_;
}


void sdx_setLargeFont (const gchar* path, gint size) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	sdxFont* _tmp2_ = NULL;
	g_return_if_fail (path != NULL);
	_tmp0_ = path;
	_tmp1_ = size;
	_tmp2_ = sdx_font_new (_tmp0_, _tmp1_);
	_g_object_unref0 (sdx_largeFont);
	sdx_largeFont = _tmp2_;
}


void sdx_setShowFps (gboolean value) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	_tmp0_ = value;
	sdx_showFps = _tmp0_;
	_tmp1_ = sdx_showFps;
	if (_tmp1_ == TRUE) {
		gchar* _tmp2_ = NULL;
		gchar* _tmp3_ = NULL;
		sdxFont* _tmp4_ = NULL;
		SDL_Color _tmp5_ = {0};
		sdxgraphicsSprite* _tmp6_ = NULL;
		sdxgraphicsSprite* _tmp7_ = NULL;
		_tmp2_ = g_strdup_printf ("%2.2f", (gdouble) 60);
		_tmp3_ = _tmp2_;
		_tmp4_ = sdx_font;
		_tmp5_ = sdx_fpsColor;
		_tmp6_ = sdx_graphics_sprite_new (_tmp3_, _tmp4_, &_tmp5_);
		_g_object_unref0 (sdx_fpsSprite);
		sdx_fpsSprite = _tmp6_;
		_g_free0 (_tmp3_);
		_tmp7_ = sdx_fpsSprite;
		_tmp7_->centered = FALSE;
	} else {
		_g_object_unref0 (sdx_fpsSprite);
		sdx_fpsSprite = NULL;
	}
}


void sdx_drawFps (void) {
	gboolean _tmp0_ = FALSE;
	_tmp0_ = sdx_showFps;
	if (_tmp0_) {
		sdxgraphicsSprite* _tmp1_ = NULL;
		gdouble _tmp2_ = 0.0;
		gchar* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		sdxFont* _tmp5_ = NULL;
		SDL_Color _tmp6_ = {0};
		sdxgraphicsSprite* _tmp7_ = NULL;
		SDL_Renderer* _tmp8_ = NULL;
		_tmp1_ = sdx_fpsSprite;
		_tmp2_ = sdx_fps;
		_tmp3_ = g_strdup_printf ("%2.2f", _tmp2_);
		_tmp4_ = _tmp3_;
		_tmp5_ = sdx_font;
		_tmp6_ = sdx_fpsColor;
		sdx_graphics_sprite_setText (_tmp1_, _tmp4_, _tmp5_, _tmp6_);
		_g_free0 (_tmp4_);
		_tmp7_ = sdx_fpsSprite;
		_tmp8_ = sdx_renderer;
		sdx_graphics_sprite_render (_tmp7_, _tmp8_, 0, 0, NULL);
	}
}


gdouble sdx_getNow (void) {
	gdouble result = 0.0;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp1_ = 0.0;
	_tmp0_ = SDL_GetPerformanceCounter ();
	_tmp1_ = sdx__freq;
	result = ((gdouble) _tmp0_) / _tmp1_;
	return result;
}


void sdx_start (void) {
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp1_ = 0.0;
	sdx_running = TRUE;
	_tmp0_ = SDL_GetPerformanceCounter ();
	_tmp1_ = sdx__freq;
	sdx__mark1 = ((gdouble) _tmp0_) / _tmp1_;
}


void sdx_update (void) {
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gint _tmp5_ = 0;
	gdouble _tmp6_ = 0.0;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	_tmp0_ = SDL_GetPerformanceCounter ();
	_tmp1_ = sdx__freq;
	sdx__mark2 = ((gdouble) _tmp0_) / _tmp1_;
	_tmp2_ = sdx__mark2;
	_tmp3_ = sdx__mark1;
	sdx_delta = _tmp2_ - _tmp3_;
	_tmp4_ = sdx__mark2;
	sdx__mark1 = _tmp4_;
	_tmp5_ = sdx__frames;
	sdx__frames = _tmp5_ + 1;
	_tmp6_ = sdx__elapsed;
	_tmp7_ = sdx_delta;
	sdx__elapsed = _tmp6_ + _tmp7_;
	_tmp8_ = sdx__elapsed;
	if (_tmp8_ > 1.0) {
		gint _tmp9_ = 0;
		gdouble _tmp10_ = 0.0;
		_tmp9_ = sdx__frames;
		_tmp10_ = sdx__elapsed;
		sdx_fps = (gdouble) ((gint) (((gdouble) _tmp9_) / _tmp10_));
		sdx__elapsed = 0.0;
		sdx__frames = 0;
	}
}


void sdx_processEvents (void) {
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_ = {0};
		SDL_EventType _tmp3_ = 0;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		 (sdx__evt);
		sdx__evt = _tmp0_;
		if (!(_tmp1_ != 0)) {
			break;
		}
		_tmp2_ = sdx__evt;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_QUIT:
			{
				sdx_running = FALSE;
				break;
			}
			case SDL_KEYDOWN:
			{
				gboolean _tmp4_ = FALSE;
				SDL_Event _tmp5_ = {0};
				SDL_KeyboardEvent _tmp6_ = {0};
				SDL_Keysym _tmp7_ = {0};
				SDL_Keycode _tmp8_ = 0;
				guint8* _tmp13_ = NULL;
				gint _tmp13__length1 = 0;
				SDL_Event _tmp14_ = {0};
				SDL_KeyboardEvent _tmp15_ = {0};
				SDL_Keysym _tmp16_ = {0};
				SDL_Keycode _tmp17_ = 0;
				guint8 _tmp18_ = 0U;
				_tmp5_ = sdx__evt;
				_tmp6_ = _tmp5_.key;
				_tmp7_ = _tmp6_.keysym;
				_tmp8_ = _tmp7_.sym;
				if (_tmp8_ < 0) {
					_tmp4_ = TRUE;
				} else {
					SDL_Event _tmp9_ = {0};
					SDL_KeyboardEvent _tmp10_ = {0};
					SDL_Keysym _tmp11_ = {0};
					SDL_Keycode _tmp12_ = 0;
					_tmp9_ = sdx__evt;
					_tmp10_ = _tmp9_.key;
					_tmp11_ = _tmp10_.keysym;
					_tmp12_ = _tmp11_.sym;
					_tmp4_ = _tmp12_ > 255;
				}
				if (_tmp4_) {
					break;
				}
				_tmp13_ = sdx_keys;
				_tmp13__length1 = sdx_keys_length1;
				_tmp14_ = sdx__evt;
				_tmp15_ = _tmp14_.key;
				_tmp16_ = _tmp15_.keysym;
				_tmp17_ = _tmp16_.sym;
				_tmp13_[_tmp17_] = (guint8) 1;
				_tmp18_ = _tmp13_[_tmp17_];
				break;
			}
			case SDL_KEYUP:
			{
				gboolean _tmp19_ = FALSE;
				SDL_Event _tmp20_ = {0};
				SDL_KeyboardEvent _tmp21_ = {0};
				SDL_Keysym _tmp22_ = {0};
				SDL_Keycode _tmp23_ = 0;
				guint8* _tmp28_ = NULL;
				gint _tmp28__length1 = 0;
				SDL_Event _tmp29_ = {0};
				SDL_KeyboardEvent _tmp30_ = {0};
				SDL_Keysym _tmp31_ = {0};
				SDL_Keycode _tmp32_ = 0;
				guint8 _tmp33_ = 0U;
				_tmp20_ = sdx__evt;
				_tmp21_ = _tmp20_.key;
				_tmp22_ = _tmp21_.keysym;
				_tmp23_ = _tmp22_.sym;
				if (_tmp23_ < 0) {
					_tmp19_ = TRUE;
				} else {
					SDL_Event _tmp24_ = {0};
					SDL_KeyboardEvent _tmp25_ = {0};
					SDL_Keysym _tmp26_ = {0};
					SDL_Keycode _tmp27_ = 0;
					_tmp24_ = sdx__evt;
					_tmp25_ = _tmp24_.key;
					_tmp26_ = _tmp25_.keysym;
					_tmp27_ = _tmp26_.sym;
					_tmp19_ = _tmp27_ > 255;
				}
				if (_tmp19_) {
					break;
				}
				_tmp28_ = sdx_keys;
				_tmp28__length1 = sdx_keys_length1;
				_tmp29_ = sdx__evt;
				_tmp30_ = _tmp29_.key;
				_tmp31_ = _tmp30_.keysym;
				_tmp32_ = _tmp31_.sym;
				_tmp28_[_tmp32_] = (guint8) 0;
				_tmp33_ = _tmp28_[_tmp32_];
				break;
			}
			case SDL_MOUSEMOTION:
			{
				SDL_Event _tmp34_ = {0};
				SDL_MouseMotionEvent _tmp35_ = {0};
				gint32 _tmp36_ = 0;
				SDL_Event _tmp37_ = {0};
				SDL_MouseMotionEvent _tmp38_ = {0};
				gint32 _tmp39_ = 0;
				_tmp34_ = sdx__evt;
				_tmp35_ = _tmp34_.motion;
				_tmp36_ = _tmp35_.x;
				sdx_mouseX = (gdouble) _tmp36_;
				_tmp37_ = sdx__evt;
				_tmp38_ = _tmp37_.motion;
				_tmp39_ = _tmp38_.y;
				sdx_mouseY = (gdouble) _tmp39_;
				break;
			}
			case SDL_MOUSEBUTTONDOWN:
			{
				sdx_mouseDown = TRUE;
				break;
			}
			case SDL_MOUSEBUTTONUP:
			{
				sdx_mouseDown = FALSE;
				break;
			}
			default:
			break;
		}
	}
}


void sdx_begin (void) {
	SDL_Renderer* _tmp0_ = NULL;
	SDL_Renderer* _tmp1_ = NULL;
	_tmp0_ = sdx_renderer;
	SDL_SetRenderDrawColor (_tmp0_, (guint8) 0, (guint8) 0, (guint8) 0, (guint8) 0);
	_tmp1_ = sdx_renderer;
	SDL_RenderClear (_tmp1_);
}


void sdx_end (void) {
	SDL_Renderer* _tmp0_ = NULL;
	_tmp0_ = sdx_renderer;
	SDL_RenderPresent (_tmp0_);
}



