#!/usr/bin/env bash

posixvalac -C \
    --vapidir ./vapis \
    --pkg sdl \
    --pkg emscripten \
    --save-temps \
    --disable-warnings \
    emcc/demo.gs

emcc `pkg-config posixvala --cflags` \
    -O2 \
    -s WASM=1 \
    -s USE_SDL=1 \
    -s USE_SDL_IMAGE=1 \
    -s USE_SDL_TTF=1  \
    --preload-file assets \
    -o emcc/index.html \
    emcc/demo.c 


