/* desktop.c generated by valac 0.34.8, the Vala compiler
 * generated from desktop.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_video.h>
#include <stdio.h>

#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))

typedef enum  {
	TEST_ERROR_Wow
} TestError;
#define TEST_ERROR test_error_quark ()

extern gint k;
gint k = 0;
extern gdouble t;
gdouble t = 0.0;
extern gdouble t1;
gdouble t1 = 0.0;
extern gdouble t2;
gdouble t2 = 0.0;
extern gdouble t3;
gdouble t3 = 0.0;
extern GRand* rnd;
GRand* rnd = NULL;
extern gboolean sdx_running;

GQuark test_error_quark (void);
gint _vala_main (const gchar* args, int args_length1);
SDL_Window* sdx_initialize (gint width, gint height, const gchar* name);
GType game_get_type (void) G_GNUC_CONST;
Game* game_new (gint width, gint height);
Game* game_construct (GType object_type, gint width, gint height);
void game_initialize (Game* self);
void game_start (Game* self);
void game_update (Game* self);
void game_draw (Game* self);
gdouble nextRand (void);


GQuark test_error_quark (void) {
	return g_quark_from_static_string ("test_error-quark");
}


/**
 * game
 * 
 *
 */
gint _vala_main (const gchar* args, int args_length1) {
	gint result = 0;
	GRand* _tmp0_ = NULL;
	SDL_Window* window = NULL;
	SDL_Window* _tmp1_ = NULL;
	Game* game = NULL;
	Game* _tmp2_ = NULL;
	Game* _tmp3_ = NULL;
	Game* _tmp4_ = NULL;
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (rnd);
	rnd = _tmp0_;
	_tmp1_ = sdx_initialize (720, 512, "Shmupwarz");
	window = _tmp1_;
	_tmp2_ = game_new (720, 512);
	game = _tmp2_;
	_tmp3_ = game;
	game_initialize (_tmp3_);
	_tmp4_ = game;
	game_start (_tmp4_);
	while (TRUE) {
		gboolean _tmp5_ = FALSE;
		gint64 _tmp6_ = 0LL;
		Game* _tmp7_ = NULL;
		gint64 _tmp8_ = 0LL;
		gdouble _tmp9_ = 0.0;
		gdouble _tmp10_ = 0.0;
		gdouble _tmp11_ = 0.0;
		gdouble _tmp12_ = 0.0;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		Game* _tmp18_ = NULL;
		_tmp5_ = sdx_running;
		if (!_tmp5_) {
			break;
		}
		_tmp6_ = g_get_real_time ();
		t1 = ((gdouble) _tmp6_) / 1000000.0;
		_tmp7_ = game;
		game_update (_tmp7_);
		_tmp8_ = g_get_real_time ();
		t2 = ((gdouble) _tmp8_) / 1000000.0;
		_tmp9_ = t2;
		_tmp10_ = t1;
		t3 = _tmp9_ - _tmp10_;
		_tmp11_ = t;
		_tmp12_ = t3;
		t = _tmp11_ + _tmp12_;
		_tmp13_ = k;
		k = _tmp13_ + 1;
		_tmp14_ = k;
		if (_tmp14_ == 1000) {
			gdouble _tmp15_ = 0.0;
			FILE* _tmp16_ = NULL;
			gdouble _tmp17_ = 0.0;
			k = 0;
			_tmp15_ = t;
			t = _tmp15_ / 1000.0;
			_tmp16_ = stdout;
			_tmp17_ = t;
			fprintf (_tmp16_, "%f\n", _tmp17_);
			t = (gdouble) 0;
		}
		_tmp18_ = game;
		game_draw (_tmp18_);
	}
	result = 0;
	_g_object_unref0 (game);
	_SDL_DestroyWindow0 (window);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}


/**
 *	random number
 */
gdouble nextRand (void) {
	gdouble result = 0.0;
	GRand* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	_tmp0_ = rnd;
	_tmp1_ = g_rand_double (_tmp0_);
	result = _tmp1_;
	return result;
}



