/* Sprite.c generated by valac 0.34.8, the Vala compiler
 * generated from Sprite.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL_pixels.h>
#include <stdlib.h>
#include <stdio.h>
#include <SDL2/SDL_video.h>
#include <SDL_ttf.h>
#include <SDL2/SDL_rect.h>


#define SDX_GRAPHICS_TYPE_SCALE (sdx_graphics_scale_get_type ())
typedef struct _sdxgraphicsScale sdxgraphicsScale;

#define SDX_GRAPHICS_TYPE_SPRITE (sdx_graphics_sprite_get_type ())
#define SDX_GRAPHICS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSprite))
#define SDX_GRAPHICS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))
#define SDX_GRAPHICS_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))

typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _sdxgraphicsSpriteClass sdxgraphicsSpriteClass;
typedef struct _sdxgraphicsSpritePrivate sdxgraphicsSpritePrivate;

#define SDX_GRAPHICS_TYPE_SURFACE (sdx_graphics_surface_get_type ())
#define SDX_GRAPHICS_SURFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_SURFACE, sdxgraphicsSurface))
#define SDX_GRAPHICS_SURFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_SURFACE, sdxgraphicsSurfaceClass))
#define SDX_GRAPHICS_IS_SURFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_SURFACE))
#define SDX_GRAPHICS_IS_SURFACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_SURFACE))
#define SDX_GRAPHICS_SURFACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_SURFACE, sdxgraphicsSurfaceClass))

typedef struct _sdxgraphicsSurface sdxgraphicsSurface;
typedef struct _sdxgraphicsSurfaceClass sdxgraphicsSurfaceClass;
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define SDX_TYPE_FONT (sdx_font_get_type ())
#define SDX_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_TYPE_FONT, sdxFont))
#define SDX_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_TYPE_FONT, sdxFontClass))
#define SDX_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_TYPE_FONT))
#define SDX_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_TYPE_FONT))
#define SDX_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_TYPE_FONT, sdxFontClass))

typedef struct _sdxFont sdxFont;
typedef struct _sdxFontClass sdxFontClass;
typedef struct _sdxgraphicsSurfacePrivate sdxgraphicsSurfacePrivate;
typedef struct _sdxFontPrivate sdxFontPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _sdxgraphicsScale {
	gdouble x;
	gdouble y;
};

struct _sdxgraphicsSprite {
	GObject parent_instance;
	sdxgraphicsSpritePrivate * priv;
	SDL_Texture* texture;
	SDL_Surface* surface;
	gint width;
	gint height;
	gint x;
	gint y;
	sdxgraphicsScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gint id;
	gchar* path;
	gboolean isText;
};

struct _sdxgraphicsSpriteClass {
	GObjectClass parent_class;
};

struct _sdxgraphicsSurface {
	GObject parent_instance;
	sdxgraphicsSurfacePrivate * priv;
	SDL_Surface* surface;
	gint width;
	gint height;
	gint id;
	gchar* path;
};

struct _sdxgraphicsSurfaceClass {
	GObjectClass parent_class;
};

struct _sdxFont {
	GObject parent_instance;
	sdxFontPrivate * priv;
	gint id;
	gchar* path;
	gint size;
	TTF_Font* innerFont;
};

struct _sdxFontClass {
	GObjectClass parent_class;
};


static gpointer sdx_graphics_sprite_parent_class = NULL;
extern sdxgraphicsSurface** sdx_graphics_sprite_cache;
extern gint sdx_graphics_sprite_cache_length1;
sdxgraphicsSurface** sdx_graphics_sprite_cache = NULL;
gint sdx_graphics_sprite_cache_length1 = 0;
extern gint sdx_graphics_sprite_uniqueId;
gint sdx_graphics_sprite_uniqueId = 0;
extern SDL_Renderer* sdx_renderer;

GType sdx_graphics_scale_get_type (void) G_GNUC_CONST;
sdxgraphicsScale* sdx_graphics_scale_dup (const sdxgraphicsScale* self);
void sdx_graphics_scale_free (sdxgraphicsScale* self);
GType sdx_graphics_sprite_get_type (void) G_GNUC_CONST;
enum  {
	SDX_GRAPHICS_SPRITE_DUMMY_PROPERTY
};
GType sdx_graphics_surface_get_type (void) G_GNUC_CONST;
GType sdx_font_get_type (void) G_GNUC_CONST;
sdxgraphicsSprite* sdx_graphics_sprite_new (const gchar* path, sdxFont* font, SDL_Color* color);
sdxgraphicsSprite* sdx_graphics_sprite_construct (GType object_type, const gchar* path, sdxFont* font, SDL_Color* color);
gint sdx_graphics_sprite_indexOfPath (sdxgraphicsSprite* self, const gchar* path);
SDL_Surface* sdx_font_render (sdxFont* self, const gchar* text, SDL_Color color);
void sdx_graphics_sprite_initialize (gint length);
sdxgraphicsSurface* sdx_graphics_surface_new (const gchar* path);
sdxgraphicsSurface* sdx_graphics_surface_construct (GType object_type, const gchar* path);
void sdx_graphics_sprite_setText (sdxgraphicsSprite* self, const gchar* text, sdxFont* font, SDL_Color color);
void sdx_graphics_sprite_render (sdxgraphicsSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip);
static void sdx_graphics_sprite_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

extern const SDL_Color SDX_COLOR_WHITE;

sdxgraphicsScale* sdx_graphics_scale_dup (const sdxgraphicsScale* self) {
	sdxgraphicsScale* dup;
	dup = g_new0 (sdxgraphicsScale, 1);
	memcpy (dup, self, sizeof (sdxgraphicsScale));
	return dup;
}


void sdx_graphics_scale_free (sdxgraphicsScale* self) {
	g_free (self);
}


GType sdx_graphics_scale_get_type (void) {
	static volatile gsize sdx_graphics_scale_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_scale_type_id__volatile)) {
		GType sdx_graphics_scale_type_id;
		sdx_graphics_scale_type_id = g_boxed_type_register_static ("sdxgraphicsScale", (GBoxedCopyFunc) sdx_graphics_scale_dup, (GBoxedFreeFunc) sdx_graphics_scale_free);
		g_once_init_leave (&sdx_graphics_scale_type_id__volatile, sdx_graphics_scale_type_id);
	}
	return sdx_graphics_scale_type_id__volatile;
}


sdxgraphicsSprite* sdx_graphics_sprite_construct (GType object_type, const gchar* path, sdxFont* font, SDL_Color* color) {
	sdxgraphicsSprite * self = NULL;
	sdxFont* _tmp0_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	self = (sdxgraphicsSprite*) g_object_new (object_type, NULL);
	_tmp0_ = font;
	if (_tmp0_ == NULL) {
		gint i = 0;
		const gchar* _tmp1_ = NULL;
		gint _tmp2_ = 0;
		gint _tmp3_ = 0;
		self->isText = FALSE;
		_tmp1_ = path;
		_tmp2_ = sdx_graphics_sprite_indexOfPath (self, _tmp1_);
		i = _tmp2_;
		_tmp3_ = i;
		if (_tmp3_ < 0) {
			FILE* _tmp4_ = NULL;
			_tmp4_ = stdout;
			fprintf (_tmp4_, "Ran out of surface cache\n");
		} else {
			SDL_Renderer* _tmp5_ = NULL;
			sdxgraphicsSurface** _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			gint _tmp7_ = 0;
			sdxgraphicsSurface* _tmp8_ = NULL;
			SDL_Surface* _tmp9_ = NULL;
			SDL_Texture* _tmp10_ = NULL;
			SDL_Texture* _tmp11_ = NULL;
			SDL_Texture* _tmp14_ = NULL;
			sdxgraphicsSurface** _tmp15_ = NULL;
			gint _tmp15__length1 = 0;
			gint _tmp16_ = 0;
			sdxgraphicsSurface* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			sdxgraphicsSurface** _tmp19_ = NULL;
			gint _tmp19__length1 = 0;
			gint _tmp20_ = 0;
			sdxgraphicsSurface* _tmp21_ = NULL;
			gint _tmp22_ = 0;
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			_tmp5_ = sdx_renderer;
			_tmp6_ = sdx_graphics_sprite_cache;
			_tmp6__length1 = sdx_graphics_sprite_cache_length1;
			_tmp7_ = i;
			_tmp8_ = _tmp6_[_tmp7_];
			_tmp9_ = _tmp8_->surface;
			_tmp10_ = SDL_CreateTextureFromSurface (_tmp5_, _tmp9_);
			_SDL_DestroyTexture0 (self->texture);
			self->texture = _tmp10_;
			_tmp11_ = self->texture;
			if (_tmp11_ == NULL) {
				FILE* _tmp12_ = NULL;
				const gchar* _tmp13_ = NULL;
				_tmp12_ = stdout;
				_tmp13_ = path;
				fprintf (_tmp12_, "Unable to load image texture %s\n", _tmp13_);
			}
			_tmp14_ = self->texture;
			SDL_SetTextureBlendMode (_tmp14_, SDL_BLENDMODE_BLEND);
			_tmp15_ = sdx_graphics_sprite_cache;
			_tmp15__length1 = sdx_graphics_sprite_cache_length1;
			_tmp16_ = i;
			_tmp17_ = _tmp15_[_tmp16_];
			_tmp18_ = _tmp17_->width;
			self->width = _tmp18_;
			_tmp19_ = sdx_graphics_sprite_cache;
			_tmp19__length1 = sdx_graphics_sprite_cache_length1;
			_tmp20_ = i;
			_tmp21_ = _tmp19_[_tmp20_];
			_tmp22_ = _tmp21_->height;
			self->height = _tmp22_;
			_tmp23_ = path;
			_tmp24_ = g_strdup (_tmp23_);
			_g_free0 (self->path);
			self->path = _tmp24_;
		}
	} else {
		SDL_Surface* surface = NULL;
		sdxFont* _tmp25_ = NULL;
		const gchar* _tmp26_ = NULL;
		SDL_Color* _tmp27_ = NULL;
		SDL_Surface* _tmp28_ = NULL;
		SDL_Surface* _tmp29_ = NULL;
		self->isText = TRUE;
		_tmp25_ = font;
		_tmp26_ = path;
		_tmp27_ = color;
		_tmp28_ = sdx_font_render (_tmp25_, _tmp26_, *_tmp27_);
		surface = _tmp28_;
		_tmp29_ = surface;
		if (_tmp29_ == NULL) {
			FILE* _tmp30_ = NULL;
			sdxFont* _tmp31_ = NULL;
			const gchar* _tmp32_ = NULL;
			_tmp30_ = stdout;
			_tmp31_ = font;
			_tmp32_ = _tmp31_->path;
			fprintf (_tmp30_, "Unable to load font surface %s\n", _tmp32_);
		} else {
			SDL_Renderer* _tmp33_ = NULL;
			SDL_Surface* _tmp34_ = NULL;
			SDL_Texture* _tmp35_ = NULL;
			SDL_Texture* _tmp36_ = NULL;
			_tmp33_ = sdx_renderer;
			_tmp34_ = surface;
			_tmp35_ = SDL_CreateTextureFromSurface (_tmp33_, _tmp34_);
			_SDL_DestroyTexture0 (self->texture);
			self->texture = _tmp35_;
			_tmp36_ = self->texture;
			if (_tmp36_ == NULL) {
				FILE* _tmp37_ = NULL;
				const gchar* _tmp38_ = NULL;
				_tmp37_ = stdout;
				_tmp38_ = path;
				fprintf (_tmp37_, "Unable to load image text %s\n", _tmp38_);
			} else {
				SDL_Texture* _tmp39_ = NULL;
				SDL_Surface* _tmp40_ = NULL;
				gint _tmp41_ = 0;
				SDL_Surface* _tmp42_ = NULL;
				gint _tmp43_ = 0;
				const gchar* _tmp44_ = NULL;
				gchar* _tmp45_ = NULL;
				_tmp39_ = self->texture;
				SDL_SetTextureBlendMode (_tmp39_, SDL_BLENDMODE_BLEND);
				_tmp40_ = surface;
				_tmp41_ = _tmp40_->w;
				self->width = _tmp41_;
				_tmp42_ = surface;
				_tmp43_ = _tmp42_->h;
				self->height = _tmp43_;
				_tmp44_ = path;
				_tmp45_ = g_strdup (_tmp44_);
				_g_free0 (self->path);
				self->path = _tmp45_;
			}
		}
		_SDL_FreeSurface0 (surface);
	}
	return self;
}


sdxgraphicsSprite* sdx_graphics_sprite_new (const gchar* path, sdxFont* font, SDL_Color* color) {
	return sdx_graphics_sprite_construct (SDX_GRAPHICS_TYPE_SPRITE, path, font, color);
}


void sdx_graphics_sprite_initialize (gint length) {
	sdxgraphicsSurface** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	_tmp0_ = sdx_graphics_sprite_cache;
	_tmp0__length1 = sdx_graphics_sprite_cache_length1;
	if (_tmp0__length1 == 0) {
		gint _tmp1_ = 0;
		sdxgraphicsSurface** _tmp2_ = NULL;
		_tmp1_ = length;
		_tmp2_ = g_new0 (sdxgraphicsSurface*, _tmp1_ + 1);
		sdx_graphics_sprite_cache = (_vala_array_free (sdx_graphics_sprite_cache, sdx_graphics_sprite_cache_length1, (GDestroyNotify) g_object_unref), NULL);
		sdx_graphics_sprite_cache = _tmp2_;
		sdx_graphics_sprite_cache_length1 = _tmp1_;
	}
}


gint sdx_graphics_sprite_indexOfPath (sdxgraphicsSprite* self, const gchar* path) {
	gint result = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (path != NULL, 0);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				sdxgraphicsSurface** _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				sdxgraphicsSurface** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				sdxgraphicsSurface* _tmp6_ = NULL;
				sdxgraphicsSurface** _tmp12_ = NULL;
				gint _tmp12__length1 = 0;
				gint _tmp13_ = 0;
				sdxgraphicsSurface* _tmp14_ = NULL;
				const gchar* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = sdx_graphics_sprite_cache;
				_tmp3__length1 = sdx_graphics_sprite_cache_length1;
				if (!(_tmp2_ < _tmp3__length1)) {
					break;
				}
				_tmp4_ = sdx_graphics_sprite_cache;
				_tmp4__length1 = sdx_graphics_sprite_cache_length1;
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				if (_tmp6_ == NULL) {
					sdxgraphicsSurface** _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint _tmp8_ = 0;
					const gchar* _tmp9_ = NULL;
					sdxgraphicsSurface* _tmp10_ = NULL;
					sdxgraphicsSurface* _tmp11_ = NULL;
					_tmp7_ = sdx_graphics_sprite_cache;
					_tmp7__length1 = sdx_graphics_sprite_cache_length1;
					_tmp8_ = i;
					_tmp9_ = path;
					_tmp10_ = sdx_graphics_surface_new (_tmp9_);
					_g_object_unref0 (_tmp7_[_tmp8_]);
					_tmp7_[_tmp8_] = _tmp10_;
					_tmp11_ = _tmp7_[_tmp8_];
				}
				_tmp12_ = sdx_graphics_sprite_cache;
				_tmp12__length1 = sdx_graphics_sprite_cache_length1;
				_tmp13_ = i;
				_tmp14_ = _tmp12_[_tmp13_];
				_tmp15_ = _tmp14_->path;
				_tmp16_ = path;
				if (g_strcmp0 (_tmp15_, _tmp16_) == 0) {
					result = i;
					return result;
				}
			}
		}
	}
	result = -1;
	return result;
}


/**
 *  Change the text value of a Sprite.fromRenderedText
 *
 * @param text string of text to generate
 * @param font used to generate text
 * @param color foregound text color (background transparent)
 */
void sdx_graphics_sprite_setText (sdxgraphicsSprite* self, const gchar* text, sdxFont* font, SDL_Color color) {
	SDL_Surface* surface = NULL;
	sdxFont* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Surface* _tmp3_ = NULL;
	SDL_Surface* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (text != NULL);
	g_return_if_fail (font != NULL);
	_tmp0_ = font;
	_tmp1_ = text;
	_tmp2_ = color;
	_tmp3_ = sdx_font_render (_tmp0_, _tmp1_, _tmp2_);
	surface = _tmp3_;
	_tmp4_ = surface;
	if (_tmp4_ == NULL) {
		FILE* _tmp5_ = NULL;
		sdxFont* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		_tmp5_ = stdout;
		_tmp6_ = font;
		_tmp7_ = _tmp6_->path;
		fprintf (_tmp5_, "Unable to set font surface %s\n", _tmp7_);
	} else {
		SDL_Renderer* _tmp8_ = NULL;
		SDL_Surface* _tmp9_ = NULL;
		SDL_Texture* _tmp10_ = NULL;
		SDL_Texture* _tmp11_ = NULL;
		_tmp8_ = sdx_renderer;
		_tmp9_ = surface;
		_tmp10_ = SDL_CreateTextureFromSurface (_tmp8_, _tmp9_);
		_SDL_DestroyTexture0 (self->texture);
		self->texture = _tmp10_;
		_tmp11_ = self->texture;
		if (_tmp11_ == NULL) {
			FILE* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			_tmp12_ = stdout;
			_tmp13_ = text;
			fprintf (_tmp12_, "Unable to set image text %s\n", _tmp13_);
		} else {
			SDL_Texture* _tmp14_ = NULL;
			SDL_Surface* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			SDL_Surface* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			const gchar* _tmp19_ = NULL;
			gchar* _tmp20_ = NULL;
			_tmp14_ = self->texture;
			SDL_SetTextureBlendMode (_tmp14_, SDL_BLENDMODE_BLEND);
			_tmp15_ = surface;
			_tmp16_ = _tmp15_->w;
			self->width = _tmp16_;
			_tmp17_ = surface;
			_tmp18_ = _tmp17_->h;
			self->height = _tmp18_;
			_tmp19_ = text;
			_tmp20_ = g_strdup (_tmp19_);
			_g_free0 (self->path);
			self->path = _tmp20_;
		}
	}
	_SDL_FreeSurface0 (surface);
}


/**
 *  Render the sprite on the Video.Renderer context
 *
 * @param renderer video context
 * @param x display coordinate
 * @param y display coordinate
 * @param clip optional clipping rectangle
 */
void sdx_graphics_sprite_render (sdxgraphicsSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip) {
	guint _tmp0_ = 0U;
	SDL_Rect* _tmp1_ = NULL;
	gint w = 0;
	sdxgraphicsScale _tmp5_ = {0};
	gdouble _tmp6_ = 0.0;
	guint _tmp7_ = 0U;
	SDL_Rect* _tmp8_ = NULL;
	gint h = 0;
	sdxgraphicsScale _tmp12_ = {0};
	gdouble _tmp13_ = 0.0;
	gint _tmp14_ = 0;
	gboolean _tmp15_ = FALSE;
	gint _tmp19_ = 0;
	gboolean _tmp20_ = FALSE;
	SDL_Texture* _tmp24_ = NULL;
	SDL_Color _tmp25_ = {0};
	guint8 _tmp26_ = 0U;
	SDL_Color _tmp27_ = {0};
	guint8 _tmp28_ = 0U;
	SDL_Color _tmp29_ = {0};
	guint8 _tmp30_ = 0U;
	SDL_Renderer* _tmp31_ = NULL;
	SDL_Texture* _tmp32_ = NULL;
	gint _tmp33_ = 0;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
	SDL_Rect _tmp37_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	_tmp1_ = clip;
	if (_tmp1_ == NULL) {
		gint _tmp2_ = 0;
		_tmp2_ = self->width;
		_tmp0_ = (guint) _tmp2_;
	} else {
		SDL_Rect* _tmp3_ = NULL;
		guint _tmp4_ = 0U;
		_tmp3_ = clip;
		_tmp4_ = (*_tmp3_).w;
		_tmp0_ = _tmp4_;
	}
	_tmp5_ = self->scale;
	_tmp6_ = _tmp5_.x;
	w = (gint) (_tmp0_ * _tmp6_);
	_tmp8_ = clip;
	if (_tmp8_ == NULL) {
		gint _tmp9_ = 0;
		_tmp9_ = self->height;
		_tmp7_ = (guint) _tmp9_;
	} else {
		SDL_Rect* _tmp10_ = NULL;
		guint _tmp11_ = 0U;
		_tmp10_ = clip;
		_tmp11_ = (*_tmp10_).h;
		_tmp7_ = _tmp11_;
	}
	_tmp12_ = self->scale;
	_tmp13_ = _tmp12_.y;
	h = (gint) (_tmp7_ * _tmp13_);
	_tmp15_ = self->centered;
	if (_tmp15_) {
		gint _tmp16_ = 0;
		gint _tmp17_ = 0;
		_tmp16_ = x;
		_tmp17_ = w;
		_tmp14_ = _tmp16_ - (_tmp17_ / 2);
	} else {
		gint _tmp18_ = 0;
		_tmp18_ = x;
		_tmp14_ = _tmp18_;
	}
	x = _tmp14_;
	_tmp20_ = self->centered;
	if (_tmp20_) {
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		_tmp21_ = y;
		_tmp22_ = h;
		_tmp19_ = _tmp21_ - (_tmp22_ / 2);
	} else {
		gint _tmp23_ = 0;
		_tmp23_ = y;
		_tmp19_ = _tmp23_;
	}
	y = _tmp19_;
	_tmp24_ = self->texture;
	_tmp25_ = self->color;
	_tmp26_ = _tmp25_.r;
	_tmp27_ = self->color;
	_tmp28_ = _tmp27_.g;
	_tmp29_ = self->color;
	_tmp30_ = _tmp29_.b;
	SDL_SetTextureColorMod (_tmp24_, _tmp26_, _tmp28_, _tmp30_);
	_tmp31_ = renderer;
	_tmp32_ = self->texture;
	_tmp33_ = x;
	_tmp34_ = y;
	_tmp35_ = w;
	_tmp36_ = h;
	_tmp37_.x = _tmp33_;
	_tmp37_.y = _tmp34_;
	_tmp37_.w = (guint) _tmp35_;
	_tmp37_.h = (guint) _tmp36_;
	SDL_RenderCopy (_tmp31_, _tmp32_, NULL, &_tmp37_);
}


static void sdx_graphics_sprite_class_init (sdxgraphicsSpriteClass * klass) {
	sdx_graphics_sprite_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = sdx_graphics_sprite_finalize;
}


static void sdx_graphics_sprite_instance_init (sdxgraphicsSprite * self) {
	sdxgraphicsScale _tmp0_ = {0};
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	memset (&_tmp0_, 0, sizeof (sdxgraphicsScale));
	_tmp0_.x = 1.0;
	_tmp0_.y = 1.0;
	self->scale = _tmp0_;
	self->color = SDX_COLOR_WHITE;
	self->centered = TRUE;
	self->layer = 0;
	_tmp1_ = sdx_graphics_sprite_uniqueId;
	sdx_graphics_sprite_uniqueId = _tmp1_ + 1;
	_tmp2_ = sdx_graphics_sprite_uniqueId;
	self->id = _tmp2_;
}


static void sdx_graphics_sprite_finalize (GObject* obj) {
	sdxgraphicsSprite * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSprite);
	_SDL_DestroyTexture0 (self->texture);
	_SDL_FreeSurface0 (self->surface);
	_g_free0 (self->path);
	G_OBJECT_CLASS (sdx_graphics_sprite_parent_class)->finalize (obj);
}


GType sdx_graphics_sprite_get_type (void) {
	static volatile gsize sdx_graphics_sprite_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_sprite_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxgraphicsSpriteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_graphics_sprite_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxgraphicsSprite), 0, (GInstanceInitFunc) sdx_graphics_sprite_instance_init, NULL };
		GType sdx_graphics_sprite_type_id;
		sdx_graphics_sprite_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxgraphicsSprite", &g_define_type_info, 0);
		g_once_init_leave (&sdx_graphics_sprite_type_id__volatile, sdx_graphics_sprite_type_id);
	}
	return sdx_graphics_sprite_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



