/* TextureAtlas.c generated by valac 0.34.8, the Vala compiler
 * generated from TextureAtlas.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SDX_GRAPHICS_TYPE_TEXTURE_ATLAS (sdx_graphics_texture_atlas_get_type ())
#define SDX_GRAPHICS_TEXTURE_ATLAS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_TEXTURE_ATLAS, sdxgraphicsTextureAtlas))
#define SDX_GRAPHICS_TEXTURE_ATLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_TEXTURE_ATLAS, sdxgraphicsTextureAtlasClass))
#define SDX_GRAPHICS_IS_TEXTURE_ATLAS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_TEXTURE_ATLAS))
#define SDX_GRAPHICS_IS_TEXTURE_ATLAS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_TEXTURE_ATLAS))
#define SDX_GRAPHICS_TEXTURE_ATLAS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_TEXTURE_ATLAS, sdxgraphicsTextureAtlasClass))

typedef struct _sdxgraphicsTextureAtlas sdxgraphicsTextureAtlas;
typedef struct _sdxgraphicsTextureAtlasClass sdxgraphicsTextureAtlasClass;
typedef struct _sdxgraphicsTextureAtlasPrivate sdxgraphicsTextureAtlasPrivate;

#define SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS (sdx_graphics_texture_atlas_innerclass_get_type ())
#define SDX_GRAPHICS_TEXTURE_ATLAS_INNERCLASS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS, sdxgraphicsTextureAtlasInnerClass))
#define SDX_GRAPHICS_TEXTURE_ATLAS_INNERCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS, sdxgraphicsTextureAtlasInnerClassClass))
#define SDX_GRAPHICS_TEXTURE_ATLAS_IS_INNERCLASS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS))
#define SDX_GRAPHICS_TEXTURE_ATLAS_IS_INNERCLASS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS))
#define SDX_GRAPHICS_TEXTURE_ATLAS_INNERCLASS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS, sdxgraphicsTextureAtlasInnerClassClass))

typedef struct _sdxgraphicsTextureAtlasInnerClass sdxgraphicsTextureAtlasInnerClass;
typedef struct _sdxgraphicsTextureAtlasInnerClassClass sdxgraphicsTextureAtlasInnerClassClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _sdxgraphicsTextureAtlasInnerClassPrivate sdxgraphicsTextureAtlasInnerClassPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _sdxgraphicsTextureAtlas {
	GObject parent_instance;
	sdxgraphicsTextureAtlasPrivate * priv;
	sdxgraphicsTextureAtlasInnerClass* x;
};

struct _sdxgraphicsTextureAtlasClass {
	GObjectClass parent_class;
};

struct _sdxgraphicsTextureAtlasInnerClass {
	GObject parent_instance;
	sdxgraphicsTextureAtlasInnerClassPrivate * priv;
	gchar* name;
};

struct _sdxgraphicsTextureAtlasInnerClassClass {
	GObjectClass parent_class;
};


static gpointer sdx_graphics_texture_atlas_parent_class = NULL;
static gpointer sdx_graphics_texture_atlas_innerclass_parent_class = NULL;

GType sdx_graphics_texture_atlas_get_type (void) G_GNUC_CONST;
GType sdx_graphics_texture_atlas_innerclass_get_type (void) G_GNUC_CONST;
enum  {
	SDX_GRAPHICS_TEXTURE_ATLAS_DUMMY_PROPERTY
};
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_new (void);
sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_construct (GType object_type);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_new (void);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_construct (GType object_type);
sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_createInner (sdxgraphicsTextureAtlas* self);
enum  {
	SDX_GRAPHICS_TEXTURE_ATLAS_INNERCLASS_DUMMY_PROPERTY
};
static void sdx_graphics_texture_atlas_innerclass_finalize (GObject* obj);
static void sdx_graphics_texture_atlas_finalize (GObject* obj);


sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_construct (GType object_type) {
	sdxgraphicsTextureAtlas * self = NULL;
	sdxgraphicsTextureAtlasInnerClass* _tmp0_ = NULL;
	self = (sdxgraphicsTextureAtlas*) g_object_new (object_type, NULL);
	_tmp0_ = sdx_graphics_texture_atlas_innerclass_new ();
	_g_object_unref0 (self->x);
	self->x = _tmp0_;
	g_print ("this is a test\n");
	return self;
}


sdxgraphicsTextureAtlas* sdx_graphics_texture_atlas_new (void) {
	return sdx_graphics_texture_atlas_construct (SDX_GRAPHICS_TYPE_TEXTURE_ATLAS);
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_createInner (sdxgraphicsTextureAtlas* self) {
	sdxgraphicsTextureAtlasInnerClass* result = NULL;
	sdxgraphicsTextureAtlasInnerClass* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = sdx_graphics_texture_atlas_innerclass_new ();
	result = _tmp0_;
	return result;
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_construct (GType object_type) {
	sdxgraphicsTextureAtlasInnerClass * self = NULL;
	gchar* _tmp0_ = NULL;
	self = (sdxgraphicsTextureAtlasInnerClass*) g_object_new (object_type, NULL);
	g_print ("this is na inner test\n");
	_tmp0_ = g_strdup ("frodo");
	_g_free0 (self->name);
	self->name = _tmp0_;
	return self;
}


sdxgraphicsTextureAtlasInnerClass* sdx_graphics_texture_atlas_innerclass_new (void) {
	return sdx_graphics_texture_atlas_innerclass_construct (SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS);
}


static void sdx_graphics_texture_atlas_innerclass_class_init (sdxgraphicsTextureAtlasInnerClassClass * klass) {
	sdx_graphics_texture_atlas_innerclass_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = sdx_graphics_texture_atlas_innerclass_finalize;
}


static void sdx_graphics_texture_atlas_innerclass_instance_init (sdxgraphicsTextureAtlasInnerClass * self) {
}


static void sdx_graphics_texture_atlas_innerclass_finalize (GObject* obj) {
	sdxgraphicsTextureAtlasInnerClass * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_GRAPHICS_TEXTURE_ATLAS_TYPE_INNERCLASS, sdxgraphicsTextureAtlasInnerClass);
	_g_free0 (self->name);
	G_OBJECT_CLASS (sdx_graphics_texture_atlas_innerclass_parent_class)->finalize (obj);
}


GType sdx_graphics_texture_atlas_innerclass_get_type (void) {
	static volatile gsize sdx_graphics_texture_atlas_innerclass_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_texture_atlas_innerclass_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxgraphicsTextureAtlasInnerClassClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_graphics_texture_atlas_innerclass_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxgraphicsTextureAtlasInnerClass), 0, (GInstanceInitFunc) sdx_graphics_texture_atlas_innerclass_instance_init, NULL };
		GType sdx_graphics_texture_atlas_innerclass_type_id;
		sdx_graphics_texture_atlas_innerclass_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxgraphicsTextureAtlasInnerClass", &g_define_type_info, 0);
		g_once_init_leave (&sdx_graphics_texture_atlas_innerclass_type_id__volatile, sdx_graphics_texture_atlas_innerclass_type_id);
	}
	return sdx_graphics_texture_atlas_innerclass_type_id__volatile;
}


static void sdx_graphics_texture_atlas_class_init (sdxgraphicsTextureAtlasClass * klass) {
	sdx_graphics_texture_atlas_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = sdx_graphics_texture_atlas_finalize;
}


static void sdx_graphics_texture_atlas_instance_init (sdxgraphicsTextureAtlas * self) {
}


static void sdx_graphics_texture_atlas_finalize (GObject* obj) {
	sdxgraphicsTextureAtlas * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SDX_GRAPHICS_TYPE_TEXTURE_ATLAS, sdxgraphicsTextureAtlas);
	_g_object_unref0 (self->x);
	G_OBJECT_CLASS (sdx_graphics_texture_atlas_parent_class)->finalize (obj);
}


/**
 * 
 */
GType sdx_graphics_texture_atlas_get_type (void) {
	static volatile gsize sdx_graphics_texture_atlas_type_id__volatile = 0;
	if (g_once_init_enter (&sdx_graphics_texture_atlas_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (sdxgraphicsTextureAtlasClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sdx_graphics_texture_atlas_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (sdxgraphicsTextureAtlas), 0, (GInstanceInitFunc) sdx_graphics_texture_atlas_instance_init, NULL };
		GType sdx_graphics_texture_atlas_type_id;
		sdx_graphics_texture_atlas_type_id = g_type_register_static (G_TYPE_OBJECT, "sdxgraphicsTextureAtlas", &g_define_type_info, 0);
		g_once_init_leave (&sdx_graphics_texture_atlas_type_id__volatile, sdx_graphics_texture_atlas_type_id);
	}
	return sdx_graphics_texture_atlas_type_id__volatile;
}



