/* JsVariant.c generated by valac 0.34.8, the Vala compiler
 * generated from JsVariant.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define UTIL_TYPE_JS_TYPE (util_js_type_get_type ())

#define UTIL_TYPE_JS_VARIANT (util_js_variant_get_type ())
#define UTIL_JS_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UTIL_TYPE_JS_VARIANT, utilJsVariant))
#define UTIL_JS_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UTIL_TYPE_JS_VARIANT, utilJsVariantClass))
#define UTIL_IS_JS_VARIANT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UTIL_TYPE_JS_VARIANT))
#define UTIL_IS_JS_VARIANT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UTIL_TYPE_JS_VARIANT))
#define UTIL_JS_VARIANT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UTIL_TYPE_JS_VARIANT, utilJsVariantClass))

typedef struct _utilJsVariant utilJsVariant;
typedef struct _utilJsVariantClass utilJsVariantClass;
typedef struct _utilJsVariantPrivate utilJsVariantPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

typedef enum  {
	UTIL_JS_TYPE_JS_INVALID,
	UTIL_JS_TYPE_JS_BOOLEAN,
	UTIL_JS_TYPE_JS_NUMBER,
	UTIL_JS_TYPE_JS_STRING,
	UTIL_JS_TYPE_JS_OBJECT,
	UTIL_JS_TYPE_JS_ARRAY
} utilJsType;

struct _utilJsVariant {
	GObject parent_instance;
	utilJsVariantPrivate * priv;
	gboolean boolean;
	gdouble number;
	gchar* string;
	GHashTable* object;
	GList* array;
	utilJsType type;
};

struct _utilJsVariantClass {
	GObjectClass parent_class;
};


static gpointer util_js_variant_parent_class = NULL;

GType util_js_type_get_type (void) G_GNUC_CONST;
GType util_js_variant_get_type (void) G_GNUC_CONST;
enum  {
	UTIL_JS_VARIANT_DUMMY_PROPERTY
};
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
utilJsVariant* util_js_variant_String (const gchar* value);
utilJsVariant* util_js_variant_new (utilJsType type, gboolean isNull);
utilJsVariant* util_js_variant_construct (GType object_type, utilJsType type, gboolean isNull);
utilJsVariant* util_js_variant_Number (gdouble value);
utilJsVariant* util_js_variant_Boolean (gboolean value);
static void _g_free0_ (gpointer var);
utilJsVariant* util_js_variant_at (utilJsVariant* self, gint index);
utilJsVariant* util_js_variant_member (utilJsVariant* self, const gchar* key);
static void util_js_variant_finalize (GObject* obj);


GType util_js_type_get_type (void) {
	static volatile gsize util_js_type_type_id__volatile = 0;
	if (g_once_init_enter (&util_js_type_type_id__volatile)) {
		static const GEnumValue values[] = {{UTIL_JS_TYPE_JS_INVALID, "UTIL_JS_TYPE_JS_INVALID", "js-invalid"}, {UTIL_JS_TYPE_JS_BOOLEAN, "UTIL_JS_TYPE_JS_BOOLEAN", "js-boolean"}, {UTIL_JS_TYPE_JS_NUMBER, "UTIL_JS_TYPE_JS_NUMBER", "js-number"}, {UTIL_JS_TYPE_JS_STRING, "UTIL_JS_TYPE_JS_STRING", "js-string"}, {UTIL_JS_TYPE_JS_OBJECT, "UTIL_JS_TYPE_JS_OBJECT", "js-object"}, {UTIL_JS_TYPE_JS_ARRAY, "UTIL_JS_TYPE_JS_ARRAY", "js-array"}, {0, NULL, NULL}};
		GType util_js_type_type_id;
		util_js_type_type_id = g_enum_register_static ("utilJsType", values);
		g_once_init_leave (&util_js_type_type_id__volatile, util_js_type_type_id);
	}
	return util_js_type_type_id__volatile;
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


utilJsVariant* util_js_variant_String (const gchar* value) {
	utilJsVariant* result = NULL;
	utilJsVariant* it = NULL;
	utilJsVariant* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (value != NULL, NULL);
	_tmp0_ = util_js_variant_new (UTIL_JS_TYPE_JS_STRING, FALSE);
	it = _tmp0_;
	_tmp1_ = value;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 (it->string);
	it->string = _tmp2_;
	result = it;
	return result;
}


utilJsVariant* util_js_variant_Number (gdouble value) {
	utilJsVariant* result = NULL;
	utilJsVariant* it = NULL;
	utilJsVariant* _tmp0_ = NULL;
	gdouble _tmp1_ = 0.0;
	_tmp0_ = util_js_variant_new (UTIL_JS_TYPE_JS_NUMBER, FALSE);
	it = _tmp0_;
	_tmp1_ = value;
	it->number = _tmp1_;
	result = it;
	return result;
}


utilJsVariant* util_js_variant_Boolean (gboolean value) {
	utilJsVariant* result = NULL;
	utilJsVariant* it = NULL;
	utilJsVariant* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	_tmp0_ = util_js_variant_new (UTIL_JS_TYPE_JS_BOOLEAN, FALSE);
	it = _tmp0_;
	_tmp1_ = value;
	it->boolean = _tmp1_;
	result = it;
	return result;
}


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static gpointer _g_hash_table_ref0 (gpointer self) {
	return self ? g_hash_table_ref (self) : NULL;
}


utilJsVariant* util_js_variant_construct (GType object_type, utilJsType type, gboolean isNull) {
	utilJsVariant * self = NULL;
	utilJsType _tmp0_ = 0;
	utilJsType _tmp1_ = 0;
	self = (utilJsVariant*) g_object_new (object_type, NULL);
	_tmp0_ = type;
	self->type = _tmp0_;
	_tmp1_ = type;
	switch (_tmp1_) {
		case UTIL_JS_TYPE_JS_BOOLEAN:
		{
			self->boolean = FALSE;
			break;
		}
		case UTIL_JS_TYPE_JS_NUMBER:
		{
			self->number = 0.0;
			break;
		}
		case UTIL_JS_TYPE_JS_STRING:
		{
			gchar* _tmp2_ = NULL;
			_tmp2_ = g_strdup ("");
			_g_free0 (self->string);
			self->string = _tmp2_;
			break;
		}
		case UTIL_JS_TYPE_JS_OBJECT:
		{
			GHashTable* _tmp3_ = NULL;
			gboolean _tmp4_ = FALSE;
			GHashTable* _tmp8_ = NULL;
			_tmp4_ = isNull;
			if (_tmp4_) {
				_g_hash_table_unref0 (_tmp3_);
				_tmp3_ = NULL;
			} else {
				GHashFunc _tmp5_ = NULL;
				GEqualFunc _tmp6_ = NULL;
				GHashTable* _tmp7_ = NULL;
				_tmp5_ = g_str_hash;
				_tmp6_ = g_str_equal;
				_tmp7_ = g_hash_table_new_full (_tmp5_, _tmp6_, _g_free0_, _g_object_unref0_);
				_g_hash_table_unref0 (_tmp3_);
				_tmp3_ = _tmp7_;
			}
			_tmp8_ = _g_hash_table_ref0 (_tmp3_);
			_g_hash_table_unref0 (self->object);
			self->object = _tmp8_;
			_g_hash_table_unref0 (_tmp3_);
			break;
		}
		case UTIL_JS_TYPE_JS_ARRAY:
		{
			__g_list_free__g_object_unref0_0 (self->array);
			self->array = NULL;
			break;
		}
		default:
		{
			break;
		}
	}
	return self;
}


utilJsVariant* util_js_variant_new (utilJsType type, gboolean isNull) {
	return util_js_variant_construct (UTIL_TYPE_JS_VARIANT, type, isNull);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


utilJsVariant* util_js_variant_at (utilJsVariant* self, gint index) {
	utilJsVariant* result = NULL;
	GList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	utilJsVariant* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->array;
	_tmp1_ = g_list_nth_data (_tmp0_, (guint) 0);
	_tmp2_ = _g_object_ref0 ((utilJsVariant*) _tmp1_);
	result = _tmp2_;
	return result;
}


utilJsVariant* util_js_variant_member (utilJsVariant* self, const gchar* key) {
	utilJsVariant* result = NULL;
	GHashTable* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gconstpointer _tmp2_ = NULL;
	utilJsVariant* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (key != NULL, NULL);
	_tmp0_ = self->object;
	_tmp1_ = key;
	_tmp2_ = g_hash_table_lookup (_tmp0_, _tmp1_);
	_tmp3_ = _g_object_ref0 ((utilJsVariant*) _tmp2_);
	result = _tmp3_;
	return result;
}


static void util_js_variant_class_init (utilJsVariantClass * klass) {
	util_js_variant_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = util_js_variant_finalize;
}


static void util_js_variant_instance_init (utilJsVariant * self) {
}


static void util_js_variant_finalize (GObject* obj) {
	utilJsVariant * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, UTIL_TYPE_JS_VARIANT, utilJsVariant);
	_g_free0 (self->string);
	_g_hash_table_unref0 (self->object);
	__g_list_free__g_object_unref0_0 (self->array);
	G_OBJECT_CLASS (util_js_variant_parent_class)->finalize (obj);
}


/**
     * Wrap a Json object
     * 
     * Arrays are represented as List<JsVariant>
     * Objects are represented as HashTable<string, JsVariant>
     */
GType util_js_variant_get_type (void) {
	static volatile gsize util_js_variant_type_id__volatile = 0;
	if (g_once_init_enter (&util_js_variant_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (utilJsVariantClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) util_js_variant_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (utilJsVariant), 0, (GInstanceInitFunc) util_js_variant_instance_init, NULL };
		GType util_js_variant_type_id;
		util_js_variant_type_id = g_type_register_static (G_TYPE_OBJECT, "utilJsVariant", &g_define_type_info, 0);
		g_once_init_leave (&util_js_variant_type_id__volatile, util_js_variant_type_id);
	}
	return util_js_variant_type_id__volatile;
}



