/* Matcher.c generated by valac 0.34.8, the Vala compiler
 * generated from Matcher.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_rect.h>
#include <float.h>
#include <math.h>


#define ENTITAS_TYPE_MATCHER (entitas_matcher_get_type ())
#define ENTITAS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENTITAS_TYPE_MATCHER, entitasMatcher))
#define ENTITAS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENTITAS_TYPE_MATCHER, entitasMatcherClass))
#define ENTITAS_IS_MATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENTITAS_TYPE_MATCHER))
#define ENTITAS_IS_MATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENTITAS_TYPE_MATCHER))
#define ENTITAS_MATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENTITAS_TYPE_MATCHER, entitasMatcherClass))

typedef struct _entitasMatcher entitasMatcher;
typedef struct _entitasMatcherClass entitasMatcherClass;
typedef struct _entitasMatcherPrivate entitasMatcherPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_POSITION (entitas_position_get_type ())
typedef struct _entitasPosition entitasPosition;

#define ENTITAS_TYPE_SCALE (entitas_scale_get_type ())
typedef struct _entitasScale entitasScale;

#define ENTITAS_TYPE_SPRITE (entitas_sprite_get_type ())

#define SDX_GRAPHICS_TYPE_SPRITE (sdx_graphics_sprite_get_type ())
#define SDX_GRAPHICS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSprite))
#define SDX_GRAPHICS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))
#define SDX_GRAPHICS_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))

typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _sdxgraphicsSpriteClass sdxgraphicsSpriteClass;
typedef struct _entitasSprite entitasSprite;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _entitasMatcher {
	GObject parent_instance;
	entitasMatcherPrivate * priv;
	gint id;
	gint* allOfIndices;
	gint allOfIndices_length1;
	guint64 allOfMask;
	gint* anyOfIndices;
	gint anyOfIndices_length1;
	guint64 anyOfMask;
	gint* noneOfIndices;
	gint noneOfIndices_length1;
	guint64 noneOfMask;
	gint* indices;
	gint indices_length1;
	gchar* toStringCache;
};

struct _entitasMatcherClass {
	GObjectClass parent_class;
};

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gdouble value;
};

struct _entitasHealth {
	gdouble current;
	gdouble maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasPosition {
	gdouble x;
	gdouble y;
};

struct _entitasScale {
	gdouble x;
	gdouble y;
};

struct _entitasSprite {
	sdxgraphicsSprite* sprite;
	gint width;
	gint height;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gdouble x;
	gdouble y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasBackground* background;
	SDL_Rect* bounds;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasPosition* position;
	entitasScale* scale;
	entitasSprite* sprite;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

typedef enum  {
	ENTITAS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_EXCEPTION_InvalidMatcherExpression,
	ENTITAS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_EXCEPTION_SingleEntity,
	ENTITAS_EXCEPTION_WorldDoesNotContainEntity
} entitasException;
#define ENTITAS_EXCEPTION entitas_exception_quark ()

static gpointer entitas_matcher_parent_class = NULL;
extern gint entitas_matcher_uniqueId;
gint entitas_matcher_uniqueId = 0;

GType entitas_matcher_get_type (void) G_GNUC_CONST;
enum  {
	ENTITAS_MATCHER_DUMMY_PROPERTY
};
entitasMatcher* entitas_matcher_new (entitasMatcher** matchers, int matchers_length1);
entitasMatcher* entitas_matcher_construct (GType object_type, entitasMatcher** matchers, int matchers_length1);
static void _vala_array_add1 (gint** array, int* length, int* size, gint value);
static void _vala_array_add2 (gint** array, int* length, int* size, gint value);
static void _vala_array_add3 (gint** array, int* length, int* size, gint value);
gint* entitas_matcher_distinctIndices (gint* indices, int indices_length1, int* result_length1);
gint* entitas_matcher_getIndices (entitasMatcher* self, int* result_length1);
gint* entitas_matcher_mergeIndices (entitasMatcher* self, int* result_length1);
static gint* _vala_array_dup1 (gint* self, int length);
entitasMatcher* entitas_matcher_anyOf (entitasMatcher* self, gint* args, int args_length1);
entitasMatcher* entitas_matcher_noneOf (entitasMatcher* self, gint* args, int args_length1);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_position_get_type (void) G_GNUC_CONST;
entitasPosition* entitas_position_dup (const entitasPosition* self);
void entitas_position_free (entitasPosition* self);
GType entitas_scale_get_type (void) G_GNUC_CONST;
entitasScale* entitas_scale_dup (const entitasScale* self);
void entitas_scale_free (entitasScale* self);
GType entitas_sprite_get_type (void) G_GNUC_CONST;
GType sdx_graphics_sprite_get_type (void) G_GNUC_CONST;
entitasSprite* entitas_sprite_dup (const entitasSprite* self);
void entitas_sprite_free (entitasSprite* self);
void entitas_sprite_copy (const entitasSprite* self, entitasSprite* dest);
void entitas_sprite_destroy (entitasSprite* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
gboolean entitas_matcher_matches (entitasMatcher* self, entitasEntity* entity);
#define ENTITAS_ACTIVE ((guint64) 0x8000000000000000LL)
static void _vala_array_add4 (gint** array, int* length, int* size, gint value);
static void _vala_array_add5 (gint** array, int* length, int* size, gint value);
static void _vala_array_add6 (gint** array, int* length, int* size, gint value);
gchar* entitas_matcher_toString (entitasMatcher* self);
gchar* entitas_matcher_componentstoString (gint* indexArray, int indexArray_length1);
gint* entitas_matcher_listToArray (GList* list, int* result_length1);
GQuark entitas_exception_quark (void);
gint* entitas_matcher_merge (entitasMatcher** matchers, int matchers_length1, int* result_length1, GError** error);
entitasMatcher* entitas_matcher_NoneOf (gint* args, int args_length1);
guint64 entitas_matcher_buildMask (gint* indices, int indices_length1);
entitasMatcher* entitas_matcher_AllOf (gint* args, int args_length1);
entitasMatcher* entitas_matcher_AnyOf (gint* args, int args_length1);
static void entitas_matcher_finalize (GObject* obj);

extern const gchar* ENTITAS_ComponentString[20];
extern const guint64 ENTITAS_POW2[65];

/**
 *  clone/merge 1 or more existing matchers
 */
static void _vala_array_add1 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add2 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add3 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


entitasMatcher* entitas_matcher_construct (GType object_type, entitasMatcher** matchers, int matchers_length1) {
	entitasMatcher * self = NULL;
	gint _tmp0_ = 0;
	entitasMatcher** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	self = (entitasMatcher*) g_object_new (object_type, NULL);
	_tmp0_ = entitas_matcher_uniqueId;
	entitas_matcher_uniqueId = _tmp0_ + 1;
	self->id = _tmp0_;
	_tmp1_ = matchers;
	_tmp1__length1 = matchers_length1;
	if (_tmp1_ != NULL) {
		gint* allOf = NULL;
		gint* _tmp2_ = NULL;
		gint allOf_length1 = 0;
		gint _allOf_size_ = 0;
		gint* anyOf = NULL;
		gint* _tmp3_ = NULL;
		gint anyOf_length1 = 0;
		gint _anyOf_size_ = 0;
		gint* noneOf = NULL;
		gint* _tmp4_ = NULL;
		gint noneOf_length1 = 0;
		gint _noneOf_size_ = 0;
		gint* _tmp42_ = NULL;
		gint _tmp42__length1 = 0;
		gint _tmp43_ = 0;
		gint* _tmp44_ = NULL;
		gint* _tmp45_ = NULL;
		gint _tmp45__length1 = 0;
		gint _tmp46_ = 0;
		gint* _tmp47_ = NULL;
		gint* _tmp48_ = NULL;
		gint _tmp48__length1 = 0;
		gint _tmp49_ = 0;
		gint* _tmp50_ = NULL;
		_tmp2_ = g_new0 (gint, 0);
		allOf = _tmp2_;
		allOf_length1 = 0;
		_allOf_size_ = allOf_length1;
		_tmp3_ = g_new0 (gint, 0);
		anyOf = _tmp3_;
		anyOf_length1 = 0;
		_anyOf_size_ = anyOf_length1;
		_tmp4_ = g_new0 (gint, 0);
		noneOf = _tmp4_;
		noneOf_length1 = 0;
		_noneOf_size_ = noneOf_length1;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp5_ = FALSE;
				_tmp5_ = TRUE;
				while (TRUE) {
					gint _tmp7_ = 0;
					entitasMatcher** _tmp8_ = NULL;
					gint _tmp8__length1 = 0;
					guint64 _tmp9_ = 0ULL;
					entitasMatcher** _tmp10_ = NULL;
					gint _tmp10__length1 = 0;
					gint _tmp11_ = 0;
					entitasMatcher* _tmp12_ = NULL;
					guint64 _tmp13_ = 0ULL;
					guint64 _tmp14_ = 0ULL;
					entitasMatcher** _tmp15_ = NULL;
					gint _tmp15__length1 = 0;
					gint _tmp16_ = 0;
					entitasMatcher* _tmp17_ = NULL;
					guint64 _tmp18_ = 0ULL;
					guint64 _tmp19_ = 0ULL;
					entitasMatcher** _tmp20_ = NULL;
					gint _tmp20__length1 = 0;
					gint _tmp21_ = 0;
					entitasMatcher* _tmp22_ = NULL;
					guint64 _tmp23_ = 0ULL;
					entitasMatcher** _tmp24_ = NULL;
					gint _tmp24__length1 = 0;
					gint _tmp25_ = 0;
					entitasMatcher* _tmp26_ = NULL;
					gint* _tmp27_ = NULL;
					gint _tmp27__length1 = 0;
					entitasMatcher** _tmp30_ = NULL;
					gint _tmp30__length1 = 0;
					gint _tmp31_ = 0;
					entitasMatcher* _tmp32_ = NULL;
					gint* _tmp33_ = NULL;
					gint _tmp33__length1 = 0;
					entitasMatcher** _tmp36_ = NULL;
					gint _tmp36__length1 = 0;
					gint _tmp37_ = 0;
					entitasMatcher* _tmp38_ = NULL;
					gint* _tmp39_ = NULL;
					gint _tmp39__length1 = 0;
					if (!_tmp5_) {
						gint _tmp6_ = 0;
						_tmp6_ = i;
						i = _tmp6_ + 1;
					}
					_tmp5_ = FALSE;
					_tmp7_ = i;
					_tmp8_ = matchers;
					_tmp8__length1 = matchers_length1;
					if (!(_tmp7_ < _tmp8__length1)) {
						break;
					}
					_tmp9_ = self->allOfMask;
					_tmp10_ = matchers;
					_tmp10__length1 = matchers_length1;
					_tmp11_ = i;
					_tmp12_ = _tmp10_[_tmp11_];
					_tmp13_ = _tmp12_->allOfMask;
					self->allOfMask = _tmp9_ | _tmp13_;
					_tmp14_ = self->anyOfMask;
					_tmp15_ = matchers;
					_tmp15__length1 = matchers_length1;
					_tmp16_ = i;
					_tmp17_ = _tmp15_[_tmp16_];
					_tmp18_ = _tmp17_->anyOfMask;
					self->anyOfMask = _tmp14_ | _tmp18_;
					_tmp19_ = self->noneOfMask;
					_tmp20_ = matchers;
					_tmp20__length1 = matchers_length1;
					_tmp21_ = i;
					_tmp22_ = _tmp20_[_tmp21_];
					_tmp23_ = _tmp22_->noneOfMask;
					self->noneOfMask = _tmp19_ | _tmp23_;
					_tmp24_ = matchers;
					_tmp24__length1 = matchers_length1;
					_tmp25_ = i;
					_tmp26_ = _tmp24_[_tmp25_];
					_tmp27_ = _tmp26_->allOfIndices;
					_tmp27__length1 = _tmp26_->allOfIndices_length1;
					{
						gint* j_collection = NULL;
						gint j_collection_length1 = 0;
						gint _j_collection_size_ = 0;
						gint j_it = 0;
						j_collection = _tmp27_;
						j_collection_length1 = _tmp27__length1;
						for (j_it = 0; j_it < _tmp27__length1; j_it = j_it + 1) {
							gint j = 0;
							j = j_collection[j_it];
							{
								gint* _tmp28_ = NULL;
								gint _tmp28__length1 = 0;
								gint _tmp29_ = 0;
								_tmp28_ = allOf;
								_tmp28__length1 = allOf_length1;
								_tmp29_ = j;
								_vala_array_add1 (&allOf, &allOf_length1, &_allOf_size_, _tmp29_);
							}
						}
					}
					_tmp30_ = matchers;
					_tmp30__length1 = matchers_length1;
					_tmp31_ = i;
					_tmp32_ = _tmp30_[_tmp31_];
					_tmp33_ = _tmp32_->anyOfIndices;
					_tmp33__length1 = _tmp32_->anyOfIndices_length1;
					{
						gint* j_collection = NULL;
						gint j_collection_length1 = 0;
						gint _j_collection_size_ = 0;
						gint j_it = 0;
						j_collection = _tmp33_;
						j_collection_length1 = _tmp33__length1;
						for (j_it = 0; j_it < _tmp33__length1; j_it = j_it + 1) {
							gint j = 0;
							j = j_collection[j_it];
							{
								gint* _tmp34_ = NULL;
								gint _tmp34__length1 = 0;
								gint _tmp35_ = 0;
								_tmp34_ = anyOf;
								_tmp34__length1 = anyOf_length1;
								_tmp35_ = j;
								_vala_array_add2 (&anyOf, &anyOf_length1, &_anyOf_size_, _tmp35_);
							}
						}
					}
					_tmp36_ = matchers;
					_tmp36__length1 = matchers_length1;
					_tmp37_ = i;
					_tmp38_ = _tmp36_[_tmp37_];
					_tmp39_ = _tmp38_->noneOfIndices;
					_tmp39__length1 = _tmp38_->noneOfIndices_length1;
					{
						gint* j_collection = NULL;
						gint j_collection_length1 = 0;
						gint _j_collection_size_ = 0;
						gint j_it = 0;
						j_collection = _tmp39_;
						j_collection_length1 = _tmp39__length1;
						for (j_it = 0; j_it < _tmp39__length1; j_it = j_it + 1) {
							gint j = 0;
							j = j_collection[j_it];
							{
								gint* _tmp40_ = NULL;
								gint _tmp40__length1 = 0;
								gint _tmp41_ = 0;
								_tmp40_ = noneOf;
								_tmp40__length1 = noneOf_length1;
								_tmp41_ = j;
								_vala_array_add3 (&noneOf, &noneOf_length1, &_noneOf_size_, _tmp41_);
							}
						}
					}
				}
			}
		}
		_tmp42_ = allOf;
		_tmp42__length1 = allOf_length1;
		_tmp44_ = entitas_matcher_distinctIndices (_tmp42_, _tmp42__length1, &_tmp43_);
		self->allOfIndices = (g_free (self->allOfIndices), NULL);
		self->allOfIndices = _tmp44_;
		self->allOfIndices_length1 = _tmp43_;
		_tmp45_ = anyOf;
		_tmp45__length1 = anyOf_length1;
		_tmp47_ = entitas_matcher_distinctIndices (_tmp45_, _tmp45__length1, &_tmp46_);
		self->anyOfIndices = (g_free (self->anyOfIndices), NULL);
		self->anyOfIndices = _tmp47_;
		self->anyOfIndices_length1 = _tmp46_;
		_tmp48_ = noneOf;
		_tmp48__length1 = noneOf_length1;
		_tmp50_ = entitas_matcher_distinctIndices (_tmp48_, _tmp48__length1, &_tmp49_);
		self->noneOfIndices = (g_free (self->noneOfIndices), NULL);
		self->noneOfIndices = _tmp50_;
		self->noneOfIndices_length1 = _tmp49_;
		noneOf = (g_free (noneOf), NULL);
		anyOf = (g_free (anyOf), NULL);
		allOf = (g_free (allOf), NULL);
	}
	return self;
}


entitasMatcher* entitas_matcher_new (entitasMatcher** matchers, int matchers_length1) {
	return entitas_matcher_construct (ENTITAS_TYPE_MATCHER, matchers, matchers_length1);
}


/**
 * A list of the component ordinals that this matches
 * @type Array<number>
 * @name entitas.Matcher#indices */
static gint* _vala_array_dup1 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


gint* entitas_matcher_getIndices (entitasMatcher* self, int* result_length1) {
	gint* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint* _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->indices;
	_tmp0__length1 = self->indices_length1;
	if (_tmp0_ == NULL) {
		gint _tmp1_ = 0;
		gint* _tmp2_ = NULL;
		_tmp2_ = entitas_matcher_mergeIndices (self, &_tmp1_);
		self->indices = (g_free (self->indices), NULL);
		self->indices = _tmp2_;
		self->indices_length1 = _tmp1_;
	}
	_tmp3_ = self->indices;
	_tmp3__length1 = self->indices_length1;
	_tmp4_ = (_tmp3_ != NULL) ? _vala_array_dup1 (_tmp3_, _tmp3__length1) : ((gpointer) _tmp3_);
	_tmp4__length1 = _tmp3__length1;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = _tmp4__length1;
	if (result_length1) {
		*result_length1 = _tmp5__length1;
	}
	result = _tmp5_;
	return result;
}


/**
 * Matches anyOf the components/indices specified
 * @params Array<entitas.IMatcher>|Array<number> args
 * @returns entitas.Matcher
 */
entitasMatcher* entitas_matcher_anyOf (entitasMatcher* self, gint* args, int args_length1) {
	entitasMatcher* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp2_ = entitas_matcher_distinctIndices (_tmp0_, _tmp0__length1, &_tmp1_);
	self->anyOfIndices = (g_free (self->anyOfIndices), NULL);
	self->anyOfIndices = _tmp2_;
	self->anyOfIndices_length1 = _tmp1_;
	self->indices = (g_free (self->indices), NULL);
	self->indices = NULL;
	self->indices_length1 = 0;
	result = self;
	return result;
}


/**
 * Matches noneOf the components/indices specified
 * @params Array<entitas.IMatcher>|Array<number> args
 * @returns entitas.Matcher
 */
entitasMatcher* entitas_matcher_noneOf (entitasMatcher* self, gint* args, int args_length1) {
	entitasMatcher* result = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp1_ = 0;
	gint* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = args;
	_tmp0__length1 = args_length1;
	_tmp2_ = entitas_matcher_distinctIndices (_tmp0_, _tmp0__length1, &_tmp1_);
	self->noneOfIndices = (g_free (self->noneOfIndices), NULL);
	self->noneOfIndices = _tmp2_;
	self->noneOfIndices_length1 = _tmp1_;
	self->indices = (g_free (self->indices), NULL);
	self->indices = NULL;
	self->indices_length1 = 0;
	result = self;
	return result;
}


/**
 * Check if the entity matches this matcher
 * @param entitas.IEntity entity	
 * @returns boolean
 */
gboolean entitas_matcher_matches (entitasMatcher* self, entitasEntity* entity) {
	gboolean result = FALSE;
	guint64 mask = 0ULL;
	entitasEntity* _tmp0_ = NULL;
	guint64 _tmp1_ = 0ULL;
	gboolean _tmp2_ = FALSE;
	guint64 _tmp3_ = 0ULL;
	gboolean matchesAllOf = FALSE;
	gboolean _tmp7_ = FALSE;
	guint64 _tmp8_ = 0ULL;
	gboolean matchesAnyOf = FALSE;
	gboolean _tmp11_ = FALSE;
	guint64 _tmp12_ = 0ULL;
	gboolean matchesNoneOf = FALSE;
	gboolean _tmp15_ = FALSE;
	gboolean _tmp16_ = FALSE;
	gboolean _tmp17_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = entity;
	_tmp1_ = (*_tmp0_).mask;
	mask = _tmp1_ ^ ENTITAS_ACTIVE;
	_tmp3_ = self->allOfMask;
	if (_tmp3_ == ((guint64) 0)) {
		_tmp2_ = TRUE;
	} else {
		guint64 _tmp4_ = 0ULL;
		guint64 _tmp5_ = 0ULL;
		guint64 _tmp6_ = 0ULL;
		_tmp4_ = mask;
		_tmp5_ = self->allOfMask;
		_tmp6_ = self->allOfMask;
		_tmp2_ = (_tmp4_ & _tmp5_) == _tmp6_;
	}
	matchesAllOf = _tmp2_;
	_tmp8_ = self->anyOfMask;
	if (_tmp8_ == ((guint64) 0)) {
		_tmp7_ = TRUE;
	} else {
		guint64 _tmp9_ = 0ULL;
		guint64 _tmp10_ = 0ULL;
		_tmp9_ = mask;
		_tmp10_ = self->anyOfMask;
		_tmp7_ = (_tmp9_ & _tmp10_) != ((guint64) 0);
	}
	matchesAnyOf = _tmp7_;
	_tmp12_ = self->noneOfMask;
	if (_tmp12_ == ((guint64) 0)) {
		_tmp11_ = TRUE;
	} else {
		guint64 _tmp13_ = 0ULL;
		guint64 _tmp14_ = 0ULL;
		_tmp13_ = mask;
		_tmp14_ = self->noneOfMask;
		_tmp11_ = (_tmp13_ & _tmp14_) == ((guint64) 0);
	}
	matchesNoneOf = _tmp11_;
	_tmp17_ = matchesAllOf;
	if (_tmp17_) {
		gboolean _tmp18_ = FALSE;
		_tmp18_ = matchesAnyOf;
		_tmp16_ = _tmp18_;
	} else {
		_tmp16_ = FALSE;
	}
	if (_tmp16_) {
		gboolean _tmp19_ = FALSE;
		_tmp19_ = matchesNoneOf;
		_tmp15_ = _tmp19_;
	} else {
		_tmp15_ = FALSE;
	}
	result = _tmp15_;
	return result;
}


/**
 * Merge list of component indices
 * @returns Array<number>
 */
static void _vala_array_add4 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add5 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


static void _vala_array_add6 (gint** array, int* length, int* size, gint value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gint, *array, *size);
	}
	(*array)[(*length)++] = value;
}


gint* entitas_matcher_mergeIndices (entitasMatcher* self, int* result_length1) {
	gint* result = NULL;
	gint* indices = NULL;
	gint* _tmp0_ = NULL;
	gint indices_length1 = 0;
	gint _indices_size_ = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp5_ = NULL;
	gint _tmp5__length1 = 0;
	gint* _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	gint* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	gint _tmp14_ = 0;
	gint* _tmp15_ = NULL;
	gint* _tmp16_ = NULL;
	gint _tmp16__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_new0 (gint, 0);
	indices = _tmp0_;
	indices_length1 = 0;
	_indices_size_ = indices_length1;
	_tmp1_ = self->allOfIndices;
	_tmp1__length1 = self->allOfIndices_length1;
	if (_tmp1_ != NULL) {
		gint* _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		_tmp2_ = self->allOfIndices;
		_tmp2__length1 = self->allOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp2_;
			i_collection_length1 = _tmp2__length1;
			for (i_it = 0; i_it < _tmp2__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					gint* _tmp3_ = NULL;
					gint _tmp3__length1 = 0;
					gint _tmp4_ = 0;
					_tmp3_ = indices;
					_tmp3__length1 = indices_length1;
					_tmp4_ = i;
					_vala_array_add4 (&indices, &indices_length1, &_indices_size_, _tmp4_);
				}
			}
		}
	}
	_tmp5_ = self->anyOfIndices;
	_tmp5__length1 = self->anyOfIndices_length1;
	if (_tmp5_ != NULL) {
		gint* _tmp6_ = NULL;
		gint _tmp6__length1 = 0;
		_tmp6_ = self->anyOfIndices;
		_tmp6__length1 = self->anyOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp6_;
			i_collection_length1 = _tmp6__length1;
			for (i_it = 0; i_it < _tmp6__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					gint* _tmp7_ = NULL;
					gint _tmp7__length1 = 0;
					gint _tmp8_ = 0;
					_tmp7_ = indices;
					_tmp7__length1 = indices_length1;
					_tmp8_ = i;
					_vala_array_add5 (&indices, &indices_length1, &_indices_size_, _tmp8_);
				}
			}
		}
	}
	_tmp9_ = self->noneOfIndices;
	_tmp9__length1 = self->noneOfIndices_length1;
	if (_tmp9_ != NULL) {
		gint* _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		_tmp10_ = self->noneOfIndices;
		_tmp10__length1 = self->noneOfIndices_length1;
		{
			gint* i_collection = NULL;
			gint i_collection_length1 = 0;
			gint _i_collection_size_ = 0;
			gint i_it = 0;
			i_collection = _tmp10_;
			i_collection_length1 = _tmp10__length1;
			for (i_it = 0; i_it < _tmp10__length1; i_it = i_it + 1) {
				gint i = 0;
				i = i_collection[i_it];
				{
					gint* _tmp11_ = NULL;
					gint _tmp11__length1 = 0;
					gint _tmp12_ = 0;
					_tmp11_ = indices;
					_tmp11__length1 = indices_length1;
					_tmp12_ = i;
					_vala_array_add6 (&indices, &indices_length1, &_indices_size_, _tmp12_);
				}
			}
		}
	}
	_tmp13_ = indices;
	_tmp13__length1 = indices_length1;
	_tmp15_ = entitas_matcher_distinctIndices (_tmp13_, _tmp13__length1, &_tmp14_);
	_tmp16_ = _tmp15_;
	_tmp16__length1 = _tmp14_;
	if (result_length1) {
		*result_length1 = _tmp16__length1;
	}
	result = _tmp16_;
	indices = (g_free (indices), NULL);
	return result;
}


/**
 * toString representation of this matcher
 * @returns string
 */
gchar* entitas_matcher_toString (entitasMatcher* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->toStringCache;
	if (_tmp0_ == NULL) {
		gchar* sb = NULL;
		gchar* _tmp1_ = NULL;
		gint* _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		gint* _tmp12_ = NULL;
		gint _tmp12__length1 = 0;
		gint* _tmp25_ = NULL;
		gint _tmp25__length1 = 0;
		const gchar* _tmp35_ = NULL;
		gchar* _tmp36_ = NULL;
		_tmp1_ = g_strdup ("");
		sb = _tmp1_;
		_tmp2_ = self->allOfIndices;
		_tmp2__length1 = self->allOfIndices_length1;
		if (_tmp2_ != NULL) {
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_ = NULL;
			const gchar* _tmp5_ = NULL;
			gint* _tmp6_ = NULL;
			gint _tmp6__length1 = 0;
			gchar* _tmp7_ = NULL;
			gchar* _tmp8_ = NULL;
			gchar* _tmp9_ = NULL;
			const gchar* _tmp10_ = NULL;
			gchar* _tmp11_ = NULL;
			_tmp3_ = sb;
			_tmp4_ = g_strconcat (_tmp3_, "AllOf(", NULL);
			_g_free0 (sb);
			sb = _tmp4_;
			_tmp5_ = sb;
			_tmp6_ = self->allOfIndices;
			_tmp6__length1 = self->allOfIndices_length1;
			_tmp7_ = entitas_matcher_componentstoString (_tmp6_, _tmp6__length1);
			_tmp8_ = _tmp7_;
			_tmp9_ = g_strconcat (_tmp5_, _tmp8_, NULL);
			_g_free0 (sb);
			sb = _tmp9_;
			_g_free0 (_tmp8_);
			_tmp10_ = sb;
			_tmp11_ = g_strconcat (_tmp10_, ")", NULL);
			_g_free0 (sb);
			sb = _tmp11_;
		}
		_tmp12_ = self->anyOfIndices;
		_tmp12__length1 = self->anyOfIndices_length1;
		if (_tmp12_ != NULL) {
			gint* _tmp13_ = NULL;
			gint _tmp13__length1 = 0;
			const gchar* _tmp16_ = NULL;
			gchar* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			gint* _tmp19_ = NULL;
			gint _tmp19__length1 = 0;
			gchar* _tmp20_ = NULL;
			gchar* _tmp21_ = NULL;
			gchar* _tmp22_ = NULL;
			const gchar* _tmp23_ = NULL;
			gchar* _tmp24_ = NULL;
			_tmp13_ = self->allOfIndices;
			_tmp13__length1 = self->allOfIndices_length1;
			if (_tmp13_ != NULL) {
				const gchar* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				_tmp14_ = sb;
				_tmp15_ = g_strconcat (_tmp14_, ".", NULL);
				_g_free0 (sb);
				sb = _tmp15_;
			}
			_tmp16_ = sb;
			_tmp17_ = g_strconcat (_tmp16_, "AnyOf(", NULL);
			_g_free0 (sb);
			sb = _tmp17_;
			_tmp18_ = sb;
			_tmp19_ = self->anyOfIndices;
			_tmp19__length1 = self->anyOfIndices_length1;
			_tmp20_ = entitas_matcher_componentstoString (_tmp19_, _tmp19__length1);
			_tmp21_ = _tmp20_;
			_tmp22_ = g_strconcat (_tmp18_, _tmp21_, NULL);
			_g_free0 (sb);
			sb = _tmp22_;
			_g_free0 (_tmp21_);
			_tmp23_ = sb;
			_tmp24_ = g_strconcat (_tmp23_, ")", NULL);
			_g_free0 (sb);
			sb = _tmp24_;
		}
		_tmp25_ = self->noneOfIndices;
		_tmp25__length1 = self->noneOfIndices_length1;
		if (_tmp25_ != NULL) {
			const gchar* _tmp26_ = NULL;
			gchar* _tmp27_ = NULL;
			const gchar* _tmp28_ = NULL;
			gint* _tmp29_ = NULL;
			gint _tmp29__length1 = 0;
			gchar* _tmp30_ = NULL;
			gchar* _tmp31_ = NULL;
			gchar* _tmp32_ = NULL;
			const gchar* _tmp33_ = NULL;
			gchar* _tmp34_ = NULL;
			_tmp26_ = sb;
			_tmp27_ = g_strconcat (_tmp26_, ".NoneOf(", NULL);
			_g_free0 (sb);
			sb = _tmp27_;
			_tmp28_ = sb;
			_tmp29_ = self->noneOfIndices;
			_tmp29__length1 = self->noneOfIndices_length1;
			_tmp30_ = entitas_matcher_componentstoString (_tmp29_, _tmp29__length1);
			_tmp31_ = _tmp30_;
			_tmp32_ = g_strconcat (_tmp28_, _tmp31_, NULL);
			_g_free0 (sb);
			sb = _tmp32_;
			_g_free0 (_tmp31_);
			_tmp33_ = sb;
			_tmp34_ = g_strconcat (_tmp33_, ")", NULL);
			_g_free0 (sb);
			sb = _tmp34_;
		}
		_tmp35_ = sb;
		_tmp36_ = g_strdup (_tmp35_);
		_g_free0 (self->toStringCache);
		self->toStringCache = _tmp36_;
		_g_free0 (sb);
	}
	_tmp37_ = self->toStringCache;
	_tmp38_ = g_strdup (_tmp37_);
	result = _tmp38_;
	return result;
}


gchar* entitas_matcher_componentstoString (gint* indexArray, int indexArray_length1) {
	gchar* result = NULL;
	gchar* sb = NULL;
	gchar* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	_tmp0_ = g_strdup ("");
	sb = _tmp0_;
	_tmp1_ = indexArray;
	_tmp1__length1 = indexArray_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp1_;
		index_collection_length1 = _tmp1__length1;
		for (index_it = 0; index_it < _tmp1__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				const gchar* _tmp2_ = NULL;
				gint _tmp3_ = 0;
				const gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				_tmp2_ = sb;
				_tmp3_ = index;
				_tmp4_ = ENTITAS_ComponentString[_tmp3_];
				_tmp5_ = g_strconcat (_tmp2_, _tmp4_, NULL);
				_g_free0 (sb);
				sb = _tmp5_;
			}
		}
	}
	result = sb;
	return result;
}


gint* entitas_matcher_listToArray (GList* list, int* result_length1) {
	gint* result = NULL;
	gint* a = NULL;
	GList* _tmp0_ = NULL;
	guint _tmp1_ = 0U;
	gint* _tmp2_ = NULL;
	gint a_length1 = 0;
	gint _a_size_ = 0;
	gint i = 0;
	GList* _tmp3_ = NULL;
	gint* _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	_tmp0_ = list;
	_tmp1_ = g_list_length (_tmp0_);
	_tmp2_ = g_new0 (gint, _tmp1_);
	a = _tmp2_;
	a_length1 = _tmp1_;
	_a_size_ = a_length1;
	i = 0;
	_tmp3_ = list;
	{
		GList* x_collection = NULL;
		GList* x_it = NULL;
		x_collection = _tmp3_;
		for (x_it = x_collection; x_it != NULL; x_it = x_it->next) {
			gint x = 0;
			x = (gint) ((gintptr) x_it->data);
			{
				gint* _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				gint _tmp6_ = 0;
				gint _tmp7_ = 0;
				_tmp4_ = a;
				_tmp4__length1 = a_length1;
				_tmp5_ = i;
				i = _tmp5_ + 1;
				_tmp6_ = x;
				_tmp4_[_tmp5_] = _tmp6_;
				_tmp7_ = _tmp4_[_tmp5_];
			}
		}
	}
	_tmp8_ = a;
	_tmp8__length1 = a_length1;
	if (result_length1) {
		*result_length1 = _tmp8__length1;
	}
	result = _tmp8_;
	return result;
}


/**
 * Get the set if distinct (non-duplicate) indices from a list
 * @param Array<number> indices
 * @returns Array<number>
 */
gint* entitas_matcher_distinctIndices (gint* indices, int indices_length1, int* result_length1) {
	gint* result = NULL;
	gboolean* indicesSet = NULL;
	gboolean* _tmp0_ = NULL;
	gint indicesSet_length1 = 0;
	gint _indicesSet_size_ = 0;
	GList* _result_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	GList* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	gint* _tmp11_ = NULL;
	gint* _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	_tmp0_ = g_new0 (gboolean, 64);
	indicesSet = _tmp0_;
	indicesSet_length1 = 64;
	_indicesSet_size_ = indicesSet_length1;
	_result_ = NULL;
	_tmp1_ = indices;
	_tmp1__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp1_;
		index_collection_length1 = _tmp1__length1;
		for (index_it = 0; index_it < _tmp1__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gboolean* _tmp2_ = NULL;
				gint _tmp2__length1 = 0;
				gint _tmp3_ = 0;
				gboolean _tmp4_ = FALSE;
				gboolean* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				gboolean _tmp8_ = FALSE;
				_tmp2_ = indicesSet;
				_tmp2__length1 = indicesSet_length1;
				_tmp3_ = index;
				_tmp4_ = _tmp2_[_tmp3_];
				if (!_tmp4_) {
					gint _tmp5_ = 0;
					_tmp5_ = index;
					_result_ = g_list_prepend (_result_, (gpointer) ((gintptr) _tmp5_));
				}
				_tmp6_ = indicesSet;
				_tmp6__length1 = indicesSet_length1;
				_tmp7_ = index;
				_tmp6_[_tmp7_] = TRUE;
				_tmp8_ = _tmp6_[_tmp7_];
			}
		}
	}
	_tmp9_ = _result_;
	_tmp11_ = entitas_matcher_listToArray (_tmp9_, &_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp12__length1 = _tmp10_;
	if (result_length1) {
		*result_length1 = _tmp12__length1;
	}
	result = _tmp12_;
	_g_list_free0 (_result_);
	indicesSet = (g_free (indicesSet), NULL);
	return result;
}


/**
 * Merge all the indices of a set of Matchers
 * @param Array<IMatcher> matchers
 * @returns Array<number>
 */
gint* entitas_matcher_merge (entitasMatcher** matchers, int matchers_length1, int* result_length1, GError** error) {
	gint* result = NULL;
	GList* indices = NULL;
	GList* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint* _tmp22_ = NULL;
	gint* _tmp23_ = NULL;
	gint _tmp23__length1 = 0;
	GError * _inner_error_ = NULL;
	indices = NULL;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_ = 0;
				entitasMatcher** _tmp3_ = NULL;
				gint _tmp3__length1 = 0;
				entitasMatcher** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				gint _tmp5_ = 0;
				entitasMatcher* _tmp6_ = NULL;
				gint* _tmp7_ = NULL;
				gint _tmp7__length1 = 0;
				entitasMatcher** _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint _tmp16_ = 0;
				entitasMatcher* _tmp17_ = NULL;
				gint* _tmp18_ = NULL;
				gint _tmp18__length1 = 0;
				gint _tmp19_ = 0;
				if (!_tmp0_) {
					gint _tmp1_ = 0;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = matchers;
				_tmp3__length1 = matchers_length1;
				if (!(_tmp2_ < (_tmp3__length1 - 1))) {
					break;
				}
				_tmp4_ = matchers;
				_tmp4__length1 = matchers_length1;
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				_tmp7_ = _tmp6_->indices;
				_tmp7__length1 = _tmp6_->indices_length1;
				if (_tmp7__length1 != 1) {
					entitasMatcher** _tmp8_ = NULL;
					gint _tmp8__length1 = 0;
					gint _tmp9_ = 0;
					entitasMatcher* _tmp10_ = NULL;
					gchar* _tmp11_ = NULL;
					gchar* _tmp12_ = NULL;
					GError* _tmp13_ = NULL;
					GError* _tmp14_ = NULL;
					_tmp8_ = matchers;
					_tmp8__length1 = matchers_length1;
					_tmp9_ = i;
					_tmp10_ = _tmp8_[_tmp9_];
					_tmp11_ = entitas_matcher_toString (_tmp10_);
					_tmp12_ = _tmp11_;
					_tmp13_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_InvalidMatcherExpression, _tmp12_);
					_tmp14_ = _tmp13_;
					_g_free0 (_tmp12_);
					_inner_error_ = _tmp14_;
					if (_inner_error_->domain == ENTITAS_EXCEPTION) {
						g_propagate_error (error, _inner_error_);
						_g_list_free0 (indices);
						return NULL;
					} else {
						_g_list_free0 (indices);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return NULL;
					}
				}
				_tmp15_ = matchers;
				_tmp15__length1 = matchers_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_];
				_tmp18_ = _tmp17_->indices;
				_tmp18__length1 = _tmp17_->indices_length1;
				_tmp19_ = _tmp18_[0];
				indices = g_list_prepend (indices, (gpointer) ((gintptr) _tmp19_));
			}
		}
	}
	_tmp20_ = indices;
	_tmp22_ = entitas_matcher_listToArray (_tmp20_, &_tmp21_);
	_tmp23_ = _tmp22_;
	_tmp23__length1 = _tmp21_;
	if (result_length1) {
		*result_length1 = _tmp23__length1;
	}
	result = _tmp23_;
	_g_list_free0 (indices);
	return result;
}


/**
 * Matches noneOf the components/indices specified
 * @params Array<entitas.IMatcher>|Array<number> args
 * @returns entitas.Matcher
 */
entitasMatcher* entitas_matcher_NoneOf (gint* args, int args_length1) {
	entitasMatcher* result = NULL;
	entitasMatcher* matcher = NULL;
	entitasMatcher* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	guint64 _tmp5_ = 0ULL;
	_tmp0_ = entitas_matcher_new (NULL, 0);
	matcher = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp3_ = entitas_matcher_distinctIndices (_tmp1_, _tmp1__length1, &_tmp2_);
	matcher->noneOfIndices = (g_free (matcher->noneOfIndices), NULL);
	matcher->noneOfIndices = _tmp3_;
	matcher->noneOfIndices_length1 = _tmp2_;
	_tmp4_ = matcher->noneOfIndices;
	_tmp4__length1 = matcher->noneOfIndices_length1;
	_tmp5_ = entitas_matcher_buildMask (_tmp4_, _tmp4__length1);
	matcher->noneOfMask = _tmp5_;
	result = matcher;
	return result;
}


/**
 * Matches allOf the components/indices specified
 * @params Array<entitas.IMatcher>|Array<number> args
 * @returns entitas.Matcher
 */
entitasMatcher* entitas_matcher_AllOf (gint* args, int args_length1) {
	entitasMatcher* result = NULL;
	entitasMatcher* matcher = NULL;
	entitasMatcher* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	guint64 _tmp5_ = 0ULL;
	_tmp0_ = entitas_matcher_new (NULL, 0);
	matcher = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp3_ = entitas_matcher_distinctIndices (_tmp1_, _tmp1__length1, &_tmp2_);
	matcher->allOfIndices = (g_free (matcher->allOfIndices), NULL);
	matcher->allOfIndices = _tmp3_;
	matcher->allOfIndices_length1 = _tmp2_;
	_tmp4_ = matcher->allOfIndices;
	_tmp4__length1 = matcher->allOfIndices_length1;
	_tmp5_ = entitas_matcher_buildMask (_tmp4_, _tmp4__length1);
	matcher->allOfMask = _tmp5_;
	result = matcher;
	return result;
}


/**
 * Matches anyOf the components/indices specified
 * @params Array<entitas.IMatcher>|Array<number> args
 * @returns entitas.Matcher
 */
entitasMatcher* entitas_matcher_AnyOf (gint* args, int args_length1) {
	entitasMatcher* result = NULL;
	entitasMatcher* matcher = NULL;
	entitasMatcher* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint _tmp2_ = 0;
	gint* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	guint64 _tmp5_ = 0ULL;
	_tmp0_ = entitas_matcher_new (NULL, 0);
	matcher = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp3_ = entitas_matcher_distinctIndices (_tmp1_, _tmp1__length1, &_tmp2_);
	matcher->anyOfIndices = (g_free (matcher->anyOfIndices), NULL);
	matcher->anyOfIndices = _tmp3_;
	matcher->anyOfIndices_length1 = _tmp2_;
	_tmp4_ = matcher->anyOfIndices;
	_tmp4__length1 = matcher->anyOfIndices_length1;
	_tmp5_ = entitas_matcher_buildMask (_tmp4_, _tmp4__length1);
	matcher->anyOfMask = _tmp5_;
	result = matcher;
	return result;
}


guint64 entitas_matcher_buildMask (gint* indices, int indices_length1) {
	guint64 result = 0ULL;
	guint64 accume = 0ULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	accume = (guint64) 0;
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				guint64 _tmp1_ = 0ULL;
				gint _tmp2_ = 0;
				guint64 _tmp3_ = 0ULL;
				_tmp1_ = accume;
				_tmp2_ = index;
				_tmp3_ = ENTITAS_POW2[_tmp2_];
				accume = _tmp1_ | _tmp3_;
			}
		}
	}
	result = accume;
	return result;
}


static void entitas_matcher_class_init (entitasMatcherClass * klass) {
	entitas_matcher_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = entitas_matcher_finalize;
}


static void entitas_matcher_instance_init (entitasMatcher * self) {
}


static void entitas_matcher_finalize (GObject* obj) {
	entitasMatcher * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENTITAS_TYPE_MATCHER, entitasMatcher);
	self->allOfIndices = (g_free (self->allOfIndices), NULL);
	self->anyOfIndices = (g_free (self->anyOfIndices), NULL);
	self->noneOfIndices = (g_free (self->noneOfIndices), NULL);
	self->indices = (g_free (self->indices), NULL);
	_g_free0 (self->toStringCache);
	G_OBJECT_CLASS (entitas_matcher_parent_class)->finalize (obj);
}


/**
 * Match entities by component
 * complile list of components to bit array for fast comparison
 *
 */
GType entitas_matcher_get_type (void) {
	static volatile gsize entitas_matcher_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_matcher_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (entitasMatcherClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) entitas_matcher_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (entitasMatcher), 0, (GInstanceInitFunc) entitas_matcher_instance_init, NULL };
		GType entitas_matcher_type_id;
		entitas_matcher_type_id = g_type_register_static (G_TYPE_OBJECT, "entitasMatcher", &g_define_type_info, 0);
		g_once_init_leave (&entitas_matcher_type_id__volatile, entitas_matcher_type_id);
	}
	return entitas_matcher_type_id__volatile;
}



