/* components.c generated by valac 0.34.8, the Vala compiler
 * generated from components.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_rect.h>


#define ENTITAS_TYPE_COMPONENTS (entitas_components_get_type ())

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_POSITION (entitas_position_get_type ())
typedef struct _entitasPosition entitasPosition;

#define ENTITAS_TYPE_SCALE (entitas_scale_get_type ())
typedef struct _entitasScale entitasScale;

#define ENTITAS_TYPE_SPRITE (entitas_sprite_get_type ())

#define SDX_GRAPHICS_TYPE_SPRITE (sdx_graphics_sprite_get_type ())
#define SDX_GRAPHICS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSprite))
#define SDX_GRAPHICS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))
#define SDX_GRAPHICS_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SDX_GRAPHICS_TYPE_SPRITE))
#define SDX_GRAPHICS_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SDX_GRAPHICS_TYPE_SPRITE, sdxgraphicsSpriteClass))

typedef struct _sdxgraphicsSprite sdxgraphicsSprite;
typedef struct _sdxgraphicsSpriteClass sdxgraphicsSpriteClass;
typedef struct _entitasSprite entitasSprite;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef struct _entitasText entitasText;
#define _g_free0(var) (var = (g_free (var), NULL))

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())
typedef struct _entitasEntity entitasEntity;
#define _entitas_background_free0(var) ((var == NULL) ? NULL : (var = (entitas_background_free (var), NULL)))
#define _entitas_bullet_free0(var) ((var == NULL) ? NULL : (var = (entitas_bullet_free (var), NULL)))
#define _entitas_enemy1_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy1_free (var), NULL)))
#define _entitas_enemy2_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy2_free (var), NULL)))
#define _entitas_enemy3_free0(var) ((var == NULL) ? NULL : (var = (entitas_enemy3_free (var), NULL)))
#define _entitas_expires_free0(var) ((var == NULL) ? NULL : (var = (entitas_expires_free (var), NULL)))
#define _entitas_health_free0(var) ((var == NULL) ? NULL : (var = (entitas_health_free (var), NULL)))
#define _entitas_hud_free0(var) ((var == NULL) ? NULL : (var = (entitas_hud_free (var), NULL)))
#define _entitas_index_free0(var) ((var == NULL) ? NULL : (var = (entitas_index_free (var), NULL)))
#define _entitas_layer_free0(var) ((var == NULL) ? NULL : (var = (entitas_layer_free (var), NULL)))
#define _entitas_position_free0(var) ((var == NULL) ? NULL : (var = (entitas_position_free (var), NULL)))
#define _entitas_scale_free0(var) ((var == NULL) ? NULL : (var = (entitas_scale_free (var), NULL)))
#define _entitas_sprite_free0(var) ((var == NULL) ? NULL : (var = (entitas_sprite_free (var), NULL)))
#define _entitas_text_free0(var) ((var == NULL) ? NULL : (var = (entitas_text_free (var), NULL)))
#define _entitas_tint_free0(var) ((var == NULL) ? NULL : (var = (entitas_tint_free (var), NULL)))
#define _entitas_tween_free0(var) ((var == NULL) ? NULL : (var = (entitas_tween_free (var), NULL)))
#define _entitas_velocity_free0(var) ((var == NULL) ? NULL : (var = (entitas_velocity_free (var), NULL)))

typedef enum  {
	ENTITAS_COMPONENTS_BackgroundComponent = 1,
	ENTITAS_COMPONENTS_BoundsComponent,
	ENTITAS_COMPONENTS_BulletComponent,
	ENTITAS_COMPONENTS_Enemy1Component,
	ENTITAS_COMPONENTS_Enemy2Component,
	ENTITAS_COMPONENTS_Enemy3Component,
	ENTITAS_COMPONENTS_ExpiresComponent,
	ENTITAS_COMPONENTS_HealthComponent,
	ENTITAS_COMPONENTS_HudComponent,
	ENTITAS_COMPONENTS_IndexComponent,
	ENTITAS_COMPONENTS_LayerComponent,
	ENTITAS_COMPONENTS_PositionComponent,
	ENTITAS_COMPONENTS_ScaleComponent,
	ENTITAS_COMPONENTS_SoundComponent,
	ENTITAS_COMPONENTS_SpriteComponent,
	ENTITAS_COMPONENTS_TextComponent,
	ENTITAS_COMPONENTS_TintComponent,
	ENTITAS_COMPONENTS_TweenComponent,
	ENTITAS_COMPONENTS_VelocityComponent,
	ENTITAS_COMPONENTS_COUNT = 19
} entitasComponents;

struct _entitasBackground {
	gboolean active;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gdouble value;
};

struct _entitasHealth {
	gdouble current;
	gdouble maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
	gint limit;
	gboolean vertical;
};

struct _entitasLayer {
	gint value;
};

struct _entitasPosition {
	gdouble x;
	gdouble y;
};

struct _entitasScale {
	gdouble x;
	gdouble y;
};

struct _entitasSprite {
	sdxgraphicsSprite* sprite;
	gint width;
	gint height;
};

struct _entitasText {
	gchar* text;
	sdxgraphicsSprite* sprite;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gdouble x;
	gdouble y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasBackground* background;
	SDL_Rect* bounds;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasPosition* position;
	entitasScale* scale;
	entitasSprite* sprite;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

typedef enum  {
	ENTITAS_EXCEPTION_EntityIsNotEnabled,
	ENTITAS_EXCEPTION_EntityAlreadyHasComponent,
	ENTITAS_EXCEPTION_EntityDoesNotHaveComponent,
	ENTITAS_EXCEPTION_InvalidMatcherExpression,
	ENTITAS_EXCEPTION_EntityIsAlreadyReleased,
	ENTITAS_EXCEPTION_SingleEntity,
	ENTITAS_EXCEPTION_WorldDoesNotContainEntity
} entitasException;
#define ENTITAS_EXCEPTION entitas_exception_quark ()


#define ENTITAS_BACKGROUND ((guint64) 0x0001)
#define ENTITAS_BOUNDS ((guint64) 0x0002)
#define ENTITAS_BULLET ((guint64) 0x0004)
#define ENTITAS_ENEMY1 ((guint64) 0x0008)
#define ENTITAS_ENEMY2 ((guint64) 0x0010)
#define ENTITAS_ENEMY3 ((guint64) 0x0020)
#define ENTITAS_EXPIRES ((guint64) 0x0040)
#define ENTITAS_HEALTH ((guint64) 0x0080)
#define ENTITAS_HUD ((guint64) 0x0100)
#define ENTITAS_INDEX ((guint64) 0x0200)
#define ENTITAS_LAYER ((guint64) 0x0400)
#define ENTITAS_POSITION ((guint64) 0x0800)
#define ENTITAS_SCALE ((guint64) 0x1000)
#define ENTITAS_SPRITE ((guint64) 0x4000)
#define ENTITAS_TEXT ((guint64) 0x8000)
#define ENTITAS_TINT ((guint64) 0x10000)
#define ENTITAS_TWEEN ((guint64) 0x20000)
#define ENTITAS_VELOCITY ((guint64) 0x40000)
#define ENTITAS_ACTIVE ((guint64) 0x8000000000000000LL)
GType entitas_components_get_type (void) G_GNUC_CONST;
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_position_get_type (void) G_GNUC_CONST;
entitasPosition* entitas_position_dup (const entitasPosition* self);
void entitas_position_free (entitasPosition* self);
GType entitas_scale_get_type (void) G_GNUC_CONST;
entitasScale* entitas_scale_dup (const entitasScale* self);
void entitas_scale_free (entitasScale* self);
GType entitas_sprite_get_type (void) G_GNUC_CONST;
GType sdx_graphics_sprite_get_type (void) G_GNUC_CONST;
entitasSprite* entitas_sprite_dup (const entitasSprite* self);
void entitas_sprite_free (entitasSprite* self);
void entitas_sprite_copy (const entitasSprite* self, entitasSprite* dest);
void entitas_sprite_destroy (entitasSprite* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
gboolean entitas_entity_hasComponent (entitasEntity *self, gint index);
gboolean entitas_entity_hasComponents (entitasEntity *self, gint* indices, int indices_length1);
gboolean entitas_entity_hasAnyComponent (entitasEntity *self, gint* indices, int indices_length1);
entitasEntity* entitas_entity_setId (entitasEntity *self, gint id);
entitasEntity* entitas_entity_setName (entitasEntity *self, const gchar* name);
entitasEntity* entitas_entity_setActive (entitasEntity *self, gboolean active);
entitasEntity* entitas_entity_setPool (entitasEntity *self, gint pool);
gboolean entitas_entity_isActive (entitasEntity *self);
gchar* entitas_entity_toString (entitasEntity *self);
entitasEntity* entitas_entity_setBackground (entitasEntity *self, gboolean value);
gboolean entitas_entity_isBackground (entitasEntity *self);
gboolean entitas_entity_hasBounds (entitasEntity *self);
entitasEntity* entitas_entity_addBounds (entitasEntity *self, gint x, gint y, gint w, gint h);
GQuark entitas_exception_quark (void);
static SDL_Rect* _sdl_video_rect_dup (SDL_Rect* self);
void entitas_world_onComponentAdded (entitasEntity* e, entitasComponents c);
entitasEntity* entitas_entity_setBounds (entitasEntity *self, gint x, gint y, gint w, gint h);
entitasEntity* entitas_entity_removeBounds (entitasEntity *self);
void entitas_world_onComponentRemoved (entitasEntity* e, entitasComponents c);
entitasEntity* entitas_entity_setBullet (entitasEntity *self, gboolean value);
gboolean entitas_entity_isBullet (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy1 (entitasEntity *self, gboolean value);
gboolean entitas_entity_isEnemy1 (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy2 (entitasEntity *self, gboolean value);
gboolean entitas_entity_isEnemy2 (entitasEntity *self);
entitasEntity* entitas_entity_setEnemy3 (entitasEntity *self, gboolean value);
gboolean entitas_entity_isEnemy3 (entitasEntity *self);
gboolean entitas_entity_hasExpires (entitasEntity *self);
entitasEntity* entitas_entity_addExpires (entitasEntity *self, gdouble value);
entitasEntity* entitas_entity_setExpires (entitasEntity *self, gdouble value);
entitasEntity* entitas_entity_removeExpires (entitasEntity *self);
gboolean entitas_entity_hasHealth (entitasEntity *self);
entitasEntity* entitas_entity_addHealth (entitasEntity *self, gdouble current, gdouble maximum);
entitasEntity* entitas_entity_setHealth (entitasEntity *self, gdouble current, gdouble maximum);
entitasEntity* entitas_entity_removeHealth (entitasEntity *self);
entitasEntity* entitas_entity_setHud (entitasEntity *self, gboolean value);
gboolean entitas_entity_isHud (entitasEntity *self);
gboolean entitas_entity_hasIndex (entitasEntity *self);
entitasEntity* entitas_entity_addIndex (entitasEntity *self, gint value, gint limit, gboolean vertical);
entitasEntity* entitas_entity_setIndex (entitasEntity *self, gint value, gint limit, gboolean vertical);
entitasEntity* entitas_entity_removeIndex (entitasEntity *self);
gboolean entitas_entity_hasLayer (entitasEntity *self);
entitasEntity* entitas_entity_addLayer (entitasEntity *self, gint value);
entitasEntity* entitas_entity_setLayer (entitasEntity *self, gint value);
entitasEntity* entitas_entity_removeLayer (entitasEntity *self);
gboolean entitas_entity_hasPosition (entitasEntity *self);
entitasEntity* entitas_entity_addPosition (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_setPosition (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_removePosition (entitasEntity *self);
gboolean entitas_entity_hasScale (entitasEntity *self);
entitasEntity* entitas_entity_addScale (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_setScale (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_removeScale (entitasEntity *self);
gboolean entitas_entity_hasSprite (entitasEntity *self);
entitasEntity* entitas_entity_addSprite (entitasEntity *self, sdxgraphicsSprite* sprite, gint width, gint height);
entitasEntity* entitas_entity_setSprite (entitasEntity *self, sdxgraphicsSprite* sprite, gint width, gint height);
entitasEntity* entitas_entity_removeSprite (entitasEntity *self);
gboolean entitas_entity_hasText (entitasEntity *self);
entitasEntity* entitas_entity_addText (entitasEntity *self, const gchar* text, sdxgraphicsSprite* texture);
entitasEntity* entitas_entity_setText (entitasEntity *self, const gchar* text, sdxgraphicsSprite* texture);
entitasEntity* entitas_entity_removeText (entitasEntity *self);
gboolean entitas_entity_hasTint (entitasEntity *self);
entitasEntity* entitas_entity_addTint (entitasEntity *self, gint r, gint g, gint b, gint a);
entitasEntity* entitas_entity_setTint (entitasEntity *self, gint r, gint g, gint b, gint a);
entitasEntity* entitas_entity_removeTint (entitasEntity *self);
gboolean entitas_entity_hasTween (entitasEntity *self);
entitasEntity* entitas_entity_addTween (entitasEntity *self, gdouble min, gdouble max, gdouble speed, gboolean repeat, gboolean active);
entitasEntity* entitas_entity_setTween (entitasEntity *self, gdouble min, gdouble max, gdouble speed, gboolean repeat, gboolean active);
entitasEntity* entitas_entity_removeTween (entitasEntity *self);
gboolean entitas_entity_hasVelocity (entitasEntity *self);
entitasEntity* entitas_entity_addVelocity (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_setVelocity (entitasEntity *self, gdouble x, gdouble y);
entitasEntity* entitas_entity_removeVelocity (entitasEntity *self);

const gchar* ENTITAS_ComponentString[20] = {"", "Background", "Bounds", "Bullet", "Enemy1", "Enemy2", "Enemy3", "Expires", "Health", "Hud", "Index", "Layer", "Position", "Scale", "Sound", "Sprite", "Text", "Tint", "Tween", "Velocity"};
extern const guint64 ENTITAS_POW2[65];

/**
* Components
*/
GType entitas_components_get_type (void) {
	static volatile gsize entitas_components_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_components_type_id__volatile)) {
		static const GEnumValue values[] = {{ENTITAS_COMPONENTS_BackgroundComponent, "ENTITAS_COMPONENTS_BackgroundComponent", "backgroundcomponent"}, {ENTITAS_COMPONENTS_BoundsComponent, "ENTITAS_COMPONENTS_BoundsComponent", "boundscomponent"}, {ENTITAS_COMPONENTS_BulletComponent, "ENTITAS_COMPONENTS_BulletComponent", "bulletcomponent"}, {ENTITAS_COMPONENTS_Enemy1Component, "ENTITAS_COMPONENTS_Enemy1Component", "enemy1component"}, {ENTITAS_COMPONENTS_Enemy2Component, "ENTITAS_COMPONENTS_Enemy2Component", "enemy2component"}, {ENTITAS_COMPONENTS_Enemy3Component, "ENTITAS_COMPONENTS_Enemy3Component", "enemy3component"}, {ENTITAS_COMPONENTS_ExpiresComponent, "ENTITAS_COMPONENTS_ExpiresComponent", "expirescomponent"}, {ENTITAS_COMPONENTS_HealthComponent, "ENTITAS_COMPONENTS_HealthComponent", "healthcomponent"}, {ENTITAS_COMPONENTS_HudComponent, "ENTITAS_COMPONENTS_HudComponent", "hudcomponent"}, {ENTITAS_COMPONENTS_IndexComponent, "ENTITAS_COMPONENTS_IndexComponent", "indexcomponent"}, {ENTITAS_COMPONENTS_LayerComponent, "ENTITAS_COMPONENTS_LayerComponent", "layercomponent"}, {ENTITAS_COMPONENTS_PositionComponent, "ENTITAS_COMPONENTS_PositionComponent", "positioncomponent"}, {ENTITAS_COMPONENTS_ScaleComponent, "ENTITAS_COMPONENTS_ScaleComponent", "scalecomponent"}, {ENTITAS_COMPONENTS_SoundComponent, "ENTITAS_COMPONENTS_SoundComponent", "soundcomponent"}, {ENTITAS_COMPONENTS_SpriteComponent, "ENTITAS_COMPONENTS_SpriteComponent", "spritecomponent"}, {ENTITAS_COMPONENTS_TextComponent, "ENTITAS_COMPONENTS_TextComponent", "textcomponent"}, {ENTITAS_COMPONENTS_TintComponent, "ENTITAS_COMPONENTS_TintComponent", "tintcomponent"}, {ENTITAS_COMPONENTS_TweenComponent, "ENTITAS_COMPONENTS_TweenComponent", "tweencomponent"}, {ENTITAS_COMPONENTS_VelocityComponent, "ENTITAS_COMPONENTS_VelocityComponent", "velocitycomponent"}, {ENTITAS_COMPONENTS_COUNT, "ENTITAS_COMPONENTS_COUNT", "count"}, {0, NULL, NULL}};
		GType entitas_components_type_id;
		entitas_components_type_id = g_enum_register_static ("entitasComponents", values);
		g_once_init_leave (&entitas_components_type_id__volatile, entitas_components_type_id);
	}
	return entitas_components_type_id__volatile;
}


entitasBackground* entitas_background_dup (const entitasBackground* self) {
	entitasBackground* dup;
	dup = g_new0 (entitasBackground, 1);
	memcpy (dup, self, sizeof (entitasBackground));
	return dup;
}


void entitas_background_free (entitasBackground* self) {
	g_free (self);
}


GType entitas_background_get_type (void) {
	static volatile gsize entitas_background_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_background_type_id__volatile)) {
		GType entitas_background_type_id;
		entitas_background_type_id = g_boxed_type_register_static ("entitasBackground", (GBoxedCopyFunc) entitas_background_dup, (GBoxedFreeFunc) entitas_background_free);
		g_once_init_leave (&entitas_background_type_id__volatile, entitas_background_type_id);
	}
	return entitas_background_type_id__volatile;
}


entitasBullet* entitas_bullet_dup (const entitasBullet* self) {
	entitasBullet* dup;
	dup = g_new0 (entitasBullet, 1);
	memcpy (dup, self, sizeof (entitasBullet));
	return dup;
}


void entitas_bullet_free (entitasBullet* self) {
	g_free (self);
}


GType entitas_bullet_get_type (void) {
	static volatile gsize entitas_bullet_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_bullet_type_id__volatile)) {
		GType entitas_bullet_type_id;
		entitas_bullet_type_id = g_boxed_type_register_static ("entitasBullet", (GBoxedCopyFunc) entitas_bullet_dup, (GBoxedFreeFunc) entitas_bullet_free);
		g_once_init_leave (&entitas_bullet_type_id__volatile, entitas_bullet_type_id);
	}
	return entitas_bullet_type_id__volatile;
}


entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self) {
	entitasEnemy1* dup;
	dup = g_new0 (entitasEnemy1, 1);
	memcpy (dup, self, sizeof (entitasEnemy1));
	return dup;
}


void entitas_enemy1_free (entitasEnemy1* self) {
	g_free (self);
}


GType entitas_enemy1_get_type (void) {
	static volatile gsize entitas_enemy1_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_enemy1_type_id__volatile)) {
		GType entitas_enemy1_type_id;
		entitas_enemy1_type_id = g_boxed_type_register_static ("entitasEnemy1", (GBoxedCopyFunc) entitas_enemy1_dup, (GBoxedFreeFunc) entitas_enemy1_free);
		g_once_init_leave (&entitas_enemy1_type_id__volatile, entitas_enemy1_type_id);
	}
	return entitas_enemy1_type_id__volatile;
}


entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self) {
	entitasEnemy2* dup;
	dup = g_new0 (entitasEnemy2, 1);
	memcpy (dup, self, sizeof (entitasEnemy2));
	return dup;
}


void entitas_enemy2_free (entitasEnemy2* self) {
	g_free (self);
}


GType entitas_enemy2_get_type (void) {
	static volatile gsize entitas_enemy2_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_enemy2_type_id__volatile)) {
		GType entitas_enemy2_type_id;
		entitas_enemy2_type_id = g_boxed_type_register_static ("entitasEnemy2", (GBoxedCopyFunc) entitas_enemy2_dup, (GBoxedFreeFunc) entitas_enemy2_free);
		g_once_init_leave (&entitas_enemy2_type_id__volatile, entitas_enemy2_type_id);
	}
	return entitas_enemy2_type_id__volatile;
}


entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self) {
	entitasEnemy3* dup;
	dup = g_new0 (entitasEnemy3, 1);
	memcpy (dup, self, sizeof (entitasEnemy3));
	return dup;
}


void entitas_enemy3_free (entitasEnemy3* self) {
	g_free (self);
}


GType entitas_enemy3_get_type (void) {
	static volatile gsize entitas_enemy3_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_enemy3_type_id__volatile)) {
		GType entitas_enemy3_type_id;
		entitas_enemy3_type_id = g_boxed_type_register_static ("entitasEnemy3", (GBoxedCopyFunc) entitas_enemy3_dup, (GBoxedFreeFunc) entitas_enemy3_free);
		g_once_init_leave (&entitas_enemy3_type_id__volatile, entitas_enemy3_type_id);
	}
	return entitas_enemy3_type_id__volatile;
}


entitasExpires* entitas_expires_dup (const entitasExpires* self) {
	entitasExpires* dup;
	dup = g_new0 (entitasExpires, 1);
	memcpy (dup, self, sizeof (entitasExpires));
	return dup;
}


void entitas_expires_free (entitasExpires* self) {
	g_free (self);
}


GType entitas_expires_get_type (void) {
	static volatile gsize entitas_expires_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_expires_type_id__volatile)) {
		GType entitas_expires_type_id;
		entitas_expires_type_id = g_boxed_type_register_static ("entitasExpires", (GBoxedCopyFunc) entitas_expires_dup, (GBoxedFreeFunc) entitas_expires_free);
		g_once_init_leave (&entitas_expires_type_id__volatile, entitas_expires_type_id);
	}
	return entitas_expires_type_id__volatile;
}


entitasHealth* entitas_health_dup (const entitasHealth* self) {
	entitasHealth* dup;
	dup = g_new0 (entitasHealth, 1);
	memcpy (dup, self, sizeof (entitasHealth));
	return dup;
}


void entitas_health_free (entitasHealth* self) {
	g_free (self);
}


GType entitas_health_get_type (void) {
	static volatile gsize entitas_health_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_health_type_id__volatile)) {
		GType entitas_health_type_id;
		entitas_health_type_id = g_boxed_type_register_static ("entitasHealth", (GBoxedCopyFunc) entitas_health_dup, (GBoxedFreeFunc) entitas_health_free);
		g_once_init_leave (&entitas_health_type_id__volatile, entitas_health_type_id);
	}
	return entitas_health_type_id__volatile;
}


entitasHud* entitas_hud_dup (const entitasHud* self) {
	entitasHud* dup;
	dup = g_new0 (entitasHud, 1);
	memcpy (dup, self, sizeof (entitasHud));
	return dup;
}


void entitas_hud_free (entitasHud* self) {
	g_free (self);
}


GType entitas_hud_get_type (void) {
	static volatile gsize entitas_hud_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_hud_type_id__volatile)) {
		GType entitas_hud_type_id;
		entitas_hud_type_id = g_boxed_type_register_static ("entitasHud", (GBoxedCopyFunc) entitas_hud_dup, (GBoxedFreeFunc) entitas_hud_free);
		g_once_init_leave (&entitas_hud_type_id__volatile, entitas_hud_type_id);
	}
	return entitas_hud_type_id__volatile;
}


entitasIndex* entitas_index_dup (const entitasIndex* self) {
	entitasIndex* dup;
	dup = g_new0 (entitasIndex, 1);
	memcpy (dup, self, sizeof (entitasIndex));
	return dup;
}


void entitas_index_free (entitasIndex* self) {
	g_free (self);
}


GType entitas_index_get_type (void) {
	static volatile gsize entitas_index_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_index_type_id__volatile)) {
		GType entitas_index_type_id;
		entitas_index_type_id = g_boxed_type_register_static ("entitasIndex", (GBoxedCopyFunc) entitas_index_dup, (GBoxedFreeFunc) entitas_index_free);
		g_once_init_leave (&entitas_index_type_id__volatile, entitas_index_type_id);
	}
	return entitas_index_type_id__volatile;
}


entitasLayer* entitas_layer_dup (const entitasLayer* self) {
	entitasLayer* dup;
	dup = g_new0 (entitasLayer, 1);
	memcpy (dup, self, sizeof (entitasLayer));
	return dup;
}


void entitas_layer_free (entitasLayer* self) {
	g_free (self);
}


GType entitas_layer_get_type (void) {
	static volatile gsize entitas_layer_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_layer_type_id__volatile)) {
		GType entitas_layer_type_id;
		entitas_layer_type_id = g_boxed_type_register_static ("entitasLayer", (GBoxedCopyFunc) entitas_layer_dup, (GBoxedFreeFunc) entitas_layer_free);
		g_once_init_leave (&entitas_layer_type_id__volatile, entitas_layer_type_id);
	}
	return entitas_layer_type_id__volatile;
}


entitasPosition* entitas_position_dup (const entitasPosition* self) {
	entitasPosition* dup;
	dup = g_new0 (entitasPosition, 1);
	memcpy (dup, self, sizeof (entitasPosition));
	return dup;
}


void entitas_position_free (entitasPosition* self) {
	g_free (self);
}


GType entitas_position_get_type (void) {
	static volatile gsize entitas_position_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_position_type_id__volatile)) {
		GType entitas_position_type_id;
		entitas_position_type_id = g_boxed_type_register_static ("entitasPosition", (GBoxedCopyFunc) entitas_position_dup, (GBoxedFreeFunc) entitas_position_free);
		g_once_init_leave (&entitas_position_type_id__volatile, entitas_position_type_id);
	}
	return entitas_position_type_id__volatile;
}


entitasScale* entitas_scale_dup (const entitasScale* self) {
	entitasScale* dup;
	dup = g_new0 (entitasScale, 1);
	memcpy (dup, self, sizeof (entitasScale));
	return dup;
}


void entitas_scale_free (entitasScale* self) {
	g_free (self);
}


GType entitas_scale_get_type (void) {
	static volatile gsize entitas_scale_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_scale_type_id__volatile)) {
		GType entitas_scale_type_id;
		entitas_scale_type_id = g_boxed_type_register_static ("entitasScale", (GBoxedCopyFunc) entitas_scale_dup, (GBoxedFreeFunc) entitas_scale_free);
		g_once_init_leave (&entitas_scale_type_id__volatile, entitas_scale_type_id);
	}
	return entitas_scale_type_id__volatile;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void entitas_sprite_copy (const entitasSprite* self, entitasSprite* dest) {
	sdxgraphicsSprite* _tmp0_ = NULL;
	sdxgraphicsSprite* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	_tmp0_ = (*self).sprite;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 ((*dest).sprite);
	(*dest).sprite = _tmp1_;
	_tmp2_ = (*self).width;
	(*dest).width = _tmp2_;
	_tmp3_ = (*self).height;
	(*dest).height = _tmp3_;
}


void entitas_sprite_destroy (entitasSprite* self) {
	_g_object_unref0 ((*self).sprite);
}


entitasSprite* entitas_sprite_dup (const entitasSprite* self) {
	entitasSprite* dup;
	dup = g_new0 (entitasSprite, 1);
	entitas_sprite_copy (self, dup);
	return dup;
}


void entitas_sprite_free (entitasSprite* self) {
	entitas_sprite_destroy (self);
	g_free (self);
}


GType entitas_sprite_get_type (void) {
	static volatile gsize entitas_sprite_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_sprite_type_id__volatile)) {
		GType entitas_sprite_type_id;
		entitas_sprite_type_id = g_boxed_type_register_static ("entitasSprite", (GBoxedCopyFunc) entitas_sprite_dup, (GBoxedFreeFunc) entitas_sprite_free);
		g_once_init_leave (&entitas_sprite_type_id__volatile, entitas_sprite_type_id);
	}
	return entitas_sprite_type_id__volatile;
}


void entitas_text_copy (const entitasText* self, entitasText* dest) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	sdxgraphicsSprite* _tmp2_ = NULL;
	sdxgraphicsSprite* _tmp3_ = NULL;
	_tmp0_ = (*self).text;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).text);
	(*dest).text = _tmp1_;
	_tmp2_ = (*self).sprite;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 ((*dest).sprite);
	(*dest).sprite = _tmp3_;
}


void entitas_text_destroy (entitasText* self) {
	_g_free0 ((*self).text);
	_g_object_unref0 ((*self).sprite);
}


entitasText* entitas_text_dup (const entitasText* self) {
	entitasText* dup;
	dup = g_new0 (entitasText, 1);
	entitas_text_copy (self, dup);
	return dup;
}


void entitas_text_free (entitasText* self) {
	entitas_text_destroy (self);
	g_free (self);
}


GType entitas_text_get_type (void) {
	static volatile gsize entitas_text_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_text_type_id__volatile)) {
		GType entitas_text_type_id;
		entitas_text_type_id = g_boxed_type_register_static ("entitasText", (GBoxedCopyFunc) entitas_text_dup, (GBoxedFreeFunc) entitas_text_free);
		g_once_init_leave (&entitas_text_type_id__volatile, entitas_text_type_id);
	}
	return entitas_text_type_id__volatile;
}


entitasTint* entitas_tint_dup (const entitasTint* self) {
	entitasTint* dup;
	dup = g_new0 (entitasTint, 1);
	memcpy (dup, self, sizeof (entitasTint));
	return dup;
}


void entitas_tint_free (entitasTint* self) {
	g_free (self);
}


GType entitas_tint_get_type (void) {
	static volatile gsize entitas_tint_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_tint_type_id__volatile)) {
		GType entitas_tint_type_id;
		entitas_tint_type_id = g_boxed_type_register_static ("entitasTint", (GBoxedCopyFunc) entitas_tint_dup, (GBoxedFreeFunc) entitas_tint_free);
		g_once_init_leave (&entitas_tint_type_id__volatile, entitas_tint_type_id);
	}
	return entitas_tint_type_id__volatile;
}


entitasTween* entitas_tween_dup (const entitasTween* self) {
	entitasTween* dup;
	dup = g_new0 (entitasTween, 1);
	memcpy (dup, self, sizeof (entitasTween));
	return dup;
}


void entitas_tween_free (entitasTween* self) {
	g_free (self);
}


GType entitas_tween_get_type (void) {
	static volatile gsize entitas_tween_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_tween_type_id__volatile)) {
		GType entitas_tween_type_id;
		entitas_tween_type_id = g_boxed_type_register_static ("entitasTween", (GBoxedCopyFunc) entitas_tween_dup, (GBoxedFreeFunc) entitas_tween_free);
		g_once_init_leave (&entitas_tween_type_id__volatile, entitas_tween_type_id);
	}
	return entitas_tween_type_id__volatile;
}


entitasVelocity* entitas_velocity_dup (const entitasVelocity* self) {
	entitasVelocity* dup;
	dup = g_new0 (entitasVelocity, 1);
	memcpy (dup, self, sizeof (entitasVelocity));
	return dup;
}


void entitas_velocity_free (entitasVelocity* self) {
	g_free (self);
}


GType entitas_velocity_get_type (void) {
	static volatile gsize entitas_velocity_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_velocity_type_id__volatile)) {
		GType entitas_velocity_type_id;
		entitas_velocity_type_id = g_boxed_type_register_static ("entitasVelocity", (GBoxedCopyFunc) entitas_velocity_dup, (GBoxedFreeFunc) entitas_velocity_free);
		g_once_init_leave (&entitas_velocity_type_id__volatile, entitas_velocity_type_id);
	}
	return entitas_velocity_type_id__volatile;
}


gboolean entitas_entity_hasComponent (entitasEntity *self, gint index) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	guint64 _tmp1_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	_tmp0_ = index;
	_tmp1_ = ENTITAS_POW2[_tmp0_];
	_tmp2_ = (*self).mask;
	result = (_tmp1_ & _tmp2_) != ((guint64) 0);
	return result;
}


gboolean entitas_entity_hasComponents (entitasEntity *self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gint _tmp1_ = 0;
				guint64 _tmp2_ = 0ULL;
				guint64 _tmp3_ = 0ULL;
				_tmp1_ = index;
				_tmp2_ = ENTITAS_POW2[_tmp1_];
				_tmp3_ = (*self).mask;
				if ((_tmp2_ & _tmp3_) == ((guint64) 0)) {
					result = FALSE;
					return result;
				}
			}
		}
	}
	result = TRUE;
	return result;
}


gboolean entitas_entity_hasAnyComponent (entitasEntity *self, gint* indices, int indices_length1) {
	gboolean result = FALSE;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	_tmp0_ = indices;
	_tmp0__length1 = indices_length1;
	{
		gint* index_collection = NULL;
		gint index_collection_length1 = 0;
		gint _index_collection_size_ = 0;
		gint index_it = 0;
		index_collection = _tmp0_;
		index_collection_length1 = _tmp0__length1;
		for (index_it = 0; index_it < _tmp0__length1; index_it = index_it + 1) {
			gint index = 0;
			index = index_collection[index_it];
			{
				gint _tmp1_ = 0;
				guint64 _tmp2_ = 0ULL;
				guint64 _tmp3_ = 0ULL;
				_tmp1_ = index;
				_tmp2_ = ENTITAS_POW2[_tmp1_];
				_tmp3_ = (*self).mask;
				if ((_tmp2_ & _tmp3_) != ((guint64) 0)) {
					result = TRUE;
					return result;
				}
			}
		}
	}
	result = FALSE;
	return result;
}


entitasEntity* entitas_entity_setId (entitasEntity *self, gint id) {
	entitasEntity* result = NULL;
	gint _tmp0_ = 0;
	_tmp0_ = id;
	(*self).id = _tmp0_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setName (entitasEntity *self, const gchar* name) {
	entitasEntity* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*self).name);
	(*self).name = _tmp1_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setActive (entitasEntity *self, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	_tmp0_ = (*self).mask;
	_tmp1_ = active;
	if (((_tmp0_ & ENTITAS_ACTIVE) == ENTITAS_ACTIVE) == _tmp1_) {
		result = &(*self);
		return result;
	}
	_tmp2_ = active;
	if (_tmp2_) {
		guint64 _tmp3_ = 0ULL;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ACTIVE;
	} else {
		guint64 _tmp4_ = 0ULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ACTIVE;
	}
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setPool (entitasEntity *self, gint pool) {
	entitasEntity* result = NULL;
	gint _tmp0_ = 0;
	_tmp0_ = pool;
	(*self).pool = _tmp0_;
	result = &(*self);
	return result;
}


gboolean entitas_entity_isActive (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ACTIVE) == ENTITAS_ACTIVE;
	return result;
}


gchar* entitas_entity_toString (entitasEntity *self) {
	gchar* result = NULL;
	gchar* sb = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	const gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gboolean seperator = FALSE;
	_tmp0_ = g_strdup ("");
	sb = _tmp0_;
	_tmp1_ = sb;
	_tmp2_ = (*self).id;
	_tmp3_ = g_strdup_printf ("%i", _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = g_strconcat (_tmp1_, _tmp4_, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = g_strconcat (_tmp6_, "(", NULL);
	_tmp8_ = _tmp7_;
	_tmp9_ = (*self).name;
	_tmp10_ = g_strconcat (_tmp8_, _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat (_tmp11_, ")", NULL);
	_g_free0 (sb);
	sb = _tmp12_;
	_g_free0 (_tmp11_);
	_g_free0 (_tmp8_);
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	seperator = FALSE;
	{
		gint i = 0;
		i = 1;
		{
			gboolean _tmp13_ = FALSE;
			_tmp13_ = TRUE;
			while (TRUE) {
				gint _tmp15_ = 0;
				gboolean _tmp16_ = FALSE;
				if (!_tmp13_) {
					gint _tmp14_ = 0;
					_tmp14_ = i;
					i = _tmp14_ + 1;
				}
				_tmp13_ = FALSE;
				if (!(i <= ((gint) ENTITAS_COMPONENTS_COUNT))) {
					break;
				}
				_tmp15_ = i;
				_tmp16_ = entitas_entity_hasComponent (&(*self), _tmp15_);
				if (_tmp16_) {
					gboolean _tmp17_ = FALSE;
					const gchar* _tmp20_ = NULL;
					gint _tmp21_ = 0;
					const gchar* _tmp22_ = NULL;
					gchar* _tmp23_ = NULL;
					_tmp17_ = seperator;
					if (_tmp17_) {
						const gchar* _tmp18_ = NULL;
						gchar* _tmp19_ = NULL;
						_tmp18_ = sb;
						_tmp19_ = g_strconcat (_tmp18_, ", ", NULL);
						_g_free0 (sb);
						sb = _tmp19_;
					}
					_tmp20_ = sb;
					_tmp21_ = i;
					_tmp22_ = ENTITAS_ComponentString[_tmp21_];
					_tmp23_ = g_strconcat (_tmp20_, _tmp22_, NULL);
					_g_free0 (sb);
					sb = _tmp23_;
					seperator = TRUE;
				}
			}
		}
	}
	result = sb;
	return result;
}


/**
 * Components:
 */
static gpointer _entitas_background_dup0 (gpointer self) {
	return self ? entitas_background_dup (self) : NULL;
}


entitasEntity* entitas_entity_setBackground (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasBackground _tmp1_ = {0};
		entitasBackground* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_background_dup0 (&_tmp1_);
		_entitas_background_free0 ((*self).background);
		(*self).background = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_BACKGROUND;
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_background_free0 ((*self).background);
		(*self).background = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_BACKGROUND;
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isBackground (entitasEntity *self) {
	gboolean result = FALSE;
	entitasBackground* _tmp0_ = NULL;
	_tmp0_ = (*self).background;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		result = TRUE;
		return result;
	}
}


gboolean entitas_entity_hasBounds (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_BOUNDS) != ((guint64) 0);
	return result;
}


static SDL_Rect* _sdl_video_rect_dup (SDL_Rect* self) {
	SDL_Rect* dup;
	dup = g_new0 (SDL_Rect, 1);
	memcpy (dup, self, sizeof (SDL_Rect));
	return dup;
}


static gpointer __sdl_video_rect_dup0 (gpointer self) {
	return self ? _sdl_video_rect_dup (self) : NULL;
}


entitasEntity* entitas_entity_addBounds (entitasEntity *self, gint x, gint y, gint w, gint h) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	SDL_Rect _tmp6_ = {0};
	SDL_Rect* _tmp7_ = NULL;
	guint64 _tmp8_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_BOUNDS) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Bounds");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_ = w;
	_tmp5_ = h;
	_tmp6_.x = _tmp2_;
	_tmp6_.y = _tmp3_;
	_tmp6_.w = (guint) _tmp4_;
	_tmp6_.h = (guint) _tmp5_;
	_tmp7_ = __sdl_video_rect_dup0 (&_tmp6_);
	_g_free0 ((*self).bounds);
	(*self).bounds = _tmp7_;
	_tmp8_ = (*self).mask;
	(*self).mask = _tmp8_ | ENTITAS_BOUNDS;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_BoundsComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setBounds (entitasEntity *self, gint x, gint y, gint w, gint h) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	SDL_Rect* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	SDL_Rect* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	SDL_Rect* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	SDL_Rect* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_BOUNDS) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Bounds");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).bounds;
	_tmp3_ = x;
	(*_tmp2_).x = _tmp3_;
	_tmp4_ = (*self).bounds;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	_tmp6_ = (*self).bounds;
	_tmp7_ = w;
	(*_tmp6_).w = (guint) _tmp7_;
	_tmp8_ = (*self).bounds;
	_tmp9_ = h;
	(*_tmp8_).h = (guint) _tmp9_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeBounds (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_BOUNDS) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Bounds");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_g_free0 ((*self).bounds);
	(*self).bounds = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_BOUNDS;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_BoundsComponent);
	result = &(*self);
	return result;
}


static gpointer _entitas_bullet_dup0 (gpointer self) {
	return self ? entitas_bullet_dup (self) : NULL;
}


entitasEntity* entitas_entity_setBullet (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasBullet _tmp1_ = {0};
		entitasBullet* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_bullet_dup0 (&_tmp1_);
		_entitas_bullet_free0 ((*self).bullet);
		(*self).bullet = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_BULLET;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_BulletComponent);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_bullet_free0 ((*self).bullet);
		(*self).bullet = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_BULLET;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_BulletComponent);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isBullet (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_BULLET) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy1_dup0 (gpointer self) {
	return self ? entitas_enemy1_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy1 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy1 _tmp1_ = {0};
		entitasEnemy1* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy1_dup0 (&_tmp1_);
		_entitas_enemy1_free0 ((*self).enemy1);
		(*self).enemy1 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY1;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy1Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy1_free0 ((*self).enemy1);
		(*self).enemy1 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY1;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy1Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy1 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY1) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy2_dup0 (gpointer self) {
	return self ? entitas_enemy2_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy2 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy2 _tmp1_ = {0};
		entitasEnemy2* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy2_dup0 (&_tmp1_);
		_entitas_enemy2_free0 ((*self).enemy2);
		(*self).enemy2 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY2;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy2Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy2_free0 ((*self).enemy2);
		(*self).enemy2 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY2;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy2Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy2 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY2) != ((guint64) 0);
	return result;
}


static gpointer _entitas_enemy3_dup0 (gpointer self) {
	return self ? entitas_enemy3_dup (self) : NULL;
}


entitasEntity* entitas_entity_setEnemy3 (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasEnemy3 _tmp1_ = {0};
		entitasEnemy3* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_enemy3_dup0 (&_tmp1_);
		_entitas_enemy3_free0 ((*self).enemy3);
		(*self).enemy3 = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_ENEMY3;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_Enemy3Component);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_enemy3_free0 ((*self).enemy3);
		(*self).enemy3 = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_ENEMY3;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_Enemy3Component);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isEnemy3 (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_ENEMY3) != ((guint64) 0);
	return result;
}


gboolean entitas_entity_hasExpires (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_EXPIRES) != ((guint64) 0);
	return result;
}


static gpointer _entitas_expires_dup0 (gpointer self) {
	return self ? entitas_expires_dup (self) : NULL;
}


entitasEntity* entitas_entity_addExpires (entitasEntity *self, gdouble value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	entitasExpires _tmp3_ = {0};
	entitasExpires* _tmp4_ = NULL;
	guint64 _tmp5_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_.value = _tmp2_;
	_tmp4_ = _entitas_expires_dup0 (&_tmp3_);
	_entitas_expires_free0 ((*self).expires);
	(*self).expires = _tmp4_;
	_tmp5_ = (*self).mask;
	(*self).mask = _tmp5_ | ENTITAS_EXPIRES;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_ExpiresComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setExpires (entitasEntity *self, gdouble value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasExpires* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).expires;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeExpires (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_EXPIRES) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Expires");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_expires_free0 ((*self).expires);
	(*self).expires = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_EXPIRES;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_ExpiresComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasHealth (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_HEALTH) != ((guint64) 0);
	return result;
}


static gpointer _entitas_health_dup0 (gpointer self) {
	return self ? entitas_health_dup (self) : NULL;
}


entitasEntity* entitas_entity_addHealth (entitasEntity *self, gdouble current, gdouble maximum) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	entitasHealth _tmp4_ = {0};
	entitasHealth* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = current;
	_tmp3_ = maximum;
	_tmp4_.current = _tmp2_;
	_tmp4_.maximum = _tmp3_;
	_tmp5_ = _entitas_health_dup0 (&_tmp4_);
	_entitas_health_free0 ((*self).health);
	(*self).health = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_HEALTH;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_HealthComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setHealth (entitasEntity *self, gdouble current, gdouble maximum) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasHealth* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	entitasHealth* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).health;
	_tmp3_ = current;
	(*_tmp2_).current = _tmp3_;
	_tmp4_ = (*self).health;
	_tmp5_ = maximum;
	(*_tmp4_).maximum = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeHealth (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_HEALTH) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Health");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_health_free0 ((*self).health);
	(*self).health = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_HEALTH;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_HealthComponent);
	result = &(*self);
	return result;
}


static gpointer _entitas_hud_dup0 (gpointer self) {
	return self ? entitas_hud_dup (self) : NULL;
}


entitasEntity* entitas_entity_setHud (entitasEntity *self, gboolean value) {
	entitasEntity* result = NULL;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = value;
	if (_tmp0_) {
		entitasHud _tmp1_ = {0};
		entitasHud* _tmp2_ = NULL;
		guint64 _tmp3_ = 0ULL;
		_tmp1_.active = TRUE;
		_tmp2_ = _entitas_hud_dup0 (&_tmp1_);
		_entitas_hud_free0 ((*self).hud);
		(*self).hud = _tmp2_;
		_tmp3_ = (*self).mask;
		(*self).mask = _tmp3_ | ENTITAS_HUD;
		entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_HudComponent);
	} else {
		guint64 _tmp4_ = 0ULL;
		_entitas_hud_free0 ((*self).hud);
		(*self).hud = NULL;
		_tmp4_ = (*self).mask;
		(*self).mask = _tmp4_ ^ ENTITAS_HUD;
		entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_HudComponent);
	}
	result = &(*self);
	return result;
}


gboolean entitas_entity_isHud (entitasEntity *self) {
	gboolean result = FALSE;
	entitasHud* _tmp0_ = NULL;
	_tmp0_ = (*self).hud;
	if (_tmp0_ == NULL) {
		result = FALSE;
		return result;
	} else {
		result = TRUE;
		return result;
	}
}


gboolean entitas_entity_hasIndex (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_INDEX) != ((guint64) 0);
	return result;
}


static gpointer _entitas_index_dup0 (gpointer self) {
	return self ? entitas_index_dup (self) : NULL;
}


entitasEntity* entitas_entity_addIndex (entitasEntity *self, gint value, gint limit, gboolean vertical) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gboolean _tmp4_ = FALSE;
	entitasIndex _tmp5_ = {0};
	entitasIndex* _tmp6_ = NULL;
	guint64 _tmp7_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_ = limit;
	_tmp4_ = vertical;
	_tmp5_.value = _tmp2_;
	_tmp5_.limit = _tmp3_;
	_tmp5_.vertical = _tmp4_;
	_tmp6_ = _entitas_index_dup0 (&_tmp5_);
	_entitas_index_free0 ((*self).index);
	(*self).index = _tmp6_;
	_tmp7_ = (*self).mask;
	(*self).mask = _tmp7_ | ENTITAS_INDEX;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_IndexComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setIndex (entitasEntity *self, gint value, gint limit, gboolean vertical) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasIndex* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	entitasIndex* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	entitasIndex* _tmp6_ = NULL;
	gboolean _tmp7_ = FALSE;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).index;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	_tmp4_ = (*self).index;
	_tmp5_ = value;
	(*_tmp4_).limit = _tmp5_;
	_tmp6_ = (*self).index;
	_tmp7_ = vertical;
	(*_tmp6_).vertical = _tmp7_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeIndex (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_INDEX) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Index");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_index_free0 ((*self).index);
	(*self).index = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_INDEX;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_IndexComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasLayer (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_LAYER) != ((guint64) 0);
	return result;
}


static gpointer _entitas_layer_dup0 (gpointer self) {
	return self ? entitas_layer_dup (self) : NULL;
}


entitasEntity* entitas_entity_addLayer (entitasEntity *self, gint value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	entitasLayer _tmp3_ = {0};
	entitasLayer* _tmp4_ = NULL;
	guint64 _tmp5_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = value;
	_tmp3_.value = _tmp2_;
	_tmp4_ = _entitas_layer_dup0 (&_tmp3_);
	_entitas_layer_free0 ((*self).layer);
	(*self).layer = _tmp4_;
	_tmp5_ = (*self).mask;
	(*self).mask = _tmp5_ | ENTITAS_LAYER;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_LayerComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setLayer (entitasEntity *self, gint value) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasLayer* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).layer;
	_tmp3_ = value;
	(*_tmp2_).value = _tmp3_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeLayer (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_LAYER) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Layer");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_layer_free0 ((*self).layer);
	(*self).layer = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_LAYER;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_LayerComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasPosition (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_POSITION) != ((guint64) 0);
	return result;
}


static gpointer _entitas_position_dup0 (gpointer self) {
	return self ? entitas_position_dup (self) : NULL;
}


entitasEntity* entitas_entity_addPosition (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	entitasPosition _tmp4_ = {0};
	entitasPosition* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_POSITION) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Unable to add Position");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_.x = _tmp2_;
	_tmp4_.y = _tmp3_;
	_tmp5_ = _entitas_position_dup0 (&_tmp4_);
	_entitas_position_free0 ((*self).position);
	(*self).position = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_POSITION;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_PositionComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setPosition (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasPosition* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	entitasPosition* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_POSITION) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Unable to set Position");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).position;
	_tmp3_ = x;
	(*_tmp2_).x = _tmp3_;
	_tmp4_ = (*self).position;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removePosition (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_POSITION) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Unable to remove Position");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_position_free0 ((*self).position);
	(*self).position = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_POSITION;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_PositionComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasScale (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_SCALE) != ((guint64) 0);
	return result;
}


static gpointer _entitas_scale_dup0 (gpointer self) {
	return self ? entitas_scale_dup (self) : NULL;
}


entitasEntity* entitas_entity_addScale (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	entitasScale _tmp4_ = {0};
	entitasScale* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SCALE) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Scale");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_.x = _tmp2_;
	_tmp4_.y = _tmp3_;
	_tmp5_ = _entitas_scale_dup0 (&_tmp4_);
	_entitas_scale_free0 ((*self).scale);
	(*self).scale = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_SCALE;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_ScaleComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setScale (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasScale* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	entitasScale* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SCALE) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Scale");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).scale;
	_tmp3_ = x;
	(*_tmp2_).x = _tmp3_;
	_tmp4_ = (*self).scale;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeScale (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SCALE) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Scale");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_scale_free0 ((*self).scale);
	(*self).scale = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_SCALE;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_ScaleComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasSprite (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_SPRITE) != ((guint64) 0);
	return result;
}


static gpointer _entitas_sprite_dup0 (gpointer self) {
	return self ? entitas_sprite_dup (self) : NULL;
}


entitasEntity* entitas_entity_addSprite (entitasEntity *self, sdxgraphicsSprite* sprite, gint width, gint height) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	sdxgraphicsSprite* _tmp2_ = NULL;
	sdxgraphicsSprite* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	entitasSprite _tmp6_ = {0};
	entitasSprite _tmp7_ = {0};
	entitasSprite* _tmp8_ = NULL;
	guint64 _tmp9_ = 0ULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (sprite != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SPRITE) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Sprite");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = sprite;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_tmp4_ = width;
	_tmp5_ = height;
	_g_object_unref0 (_tmp6_.sprite);
	_tmp6_.sprite = _tmp3_;
	_tmp6_.width = _tmp4_;
	_tmp6_.height = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp8_ = _entitas_sprite_dup0 (&_tmp7_);
	_entitas_sprite_free0 ((*self).sprite);
	(*self).sprite = _tmp8_;
	entitas_sprite_destroy (&_tmp7_);
	_tmp9_ = (*self).mask;
	(*self).mask = _tmp9_ | ENTITAS_SPRITE;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_SpriteComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setSprite (entitasEntity *self, sdxgraphicsSprite* sprite, gint width, gint height) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasSprite* _tmp2_ = NULL;
	sdxgraphicsSprite* _tmp3_ = NULL;
	sdxgraphicsSprite* _tmp4_ = NULL;
	entitasSprite* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	entitasSprite* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (sprite != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SPRITE) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Sprite");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).sprite;
	_tmp3_ = sprite;
	_tmp4_ = _g_object_ref0 (_tmp3_);
	_g_object_unref0 ((*_tmp2_).sprite);
	(*_tmp2_).sprite = _tmp4_;
	_tmp5_ = (*self).sprite;
	_tmp6_ = width;
	(*_tmp5_).width = _tmp6_;
	_tmp7_ = (*self).sprite;
	_tmp8_ = height;
	(*_tmp7_).height = _tmp8_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeSprite (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_SPRITE) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Sprite");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_sprite_free0 ((*self).sprite);
	(*self).sprite = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_SPRITE;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_SpriteComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasText (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TEXT) != ((guint64) 0);
	return result;
}


static gpointer _entitas_text_dup0 (gpointer self) {
	return self ? entitas_text_dup (self) : NULL;
}


entitasEntity* entitas_entity_addText (entitasEntity *self, const gchar* text, sdxgraphicsSprite* texture) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	sdxgraphicsSprite* _tmp4_ = NULL;
	sdxgraphicsSprite* _tmp5_ = NULL;
	entitasText _tmp6_ = {0};
	entitasText _tmp7_ = {0};
	entitasText* _tmp8_ = NULL;
	guint64 _tmp9_ = 0ULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (texture != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = text;
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = texture;
	_tmp5_ = _g_object_ref0 (_tmp4_);
	_g_free0 (_tmp6_.text);
	_tmp6_.text = _tmp3_;
	_g_object_unref0 (_tmp6_.sprite);
	_tmp6_.sprite = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp8_ = _entitas_text_dup0 (&_tmp7_);
	_entitas_text_free0 ((*self).text);
	(*self).text = _tmp8_;
	entitas_text_destroy (&_tmp7_);
	_tmp9_ = (*self).mask;
	(*self).mask = _tmp9_ | ENTITAS_TEXT;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TextComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setText (entitasEntity *self, const gchar* text, sdxgraphicsSprite* texture) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasText* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	entitasText* _tmp5_ = NULL;
	sdxgraphicsSprite* _tmp6_ = NULL;
	sdxgraphicsSprite* _tmp7_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (texture != NULL, NULL);
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).text;
	_tmp3_ = text;
	_tmp4_ = g_strdup (_tmp3_);
	_g_free0 ((*_tmp2_).text);
	(*_tmp2_).text = _tmp4_;
	_tmp5_ = (*self).text;
	_tmp6_ = texture;
	_tmp7_ = _g_object_ref0 (_tmp6_);
	_g_object_unref0 ((*_tmp5_).sprite);
	(*_tmp5_).sprite = _tmp7_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeText (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TEXT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Text");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_text_free0 ((*self).text);
	(*self).text = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TEXT;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TextComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasTint (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TINT) != ((guint64) 0);
	return result;
}


static gpointer _entitas_tint_dup0 (gpointer self) {
	return self ? entitas_tint_dup (self) : NULL;
}


entitasEntity* entitas_entity_addTint (entitasEntity *self, gint r, gint g, gint b, gint a) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	entitasTint _tmp6_ = {0};
	entitasTint* _tmp7_ = NULL;
	guint64 _tmp8_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = r;
	_tmp3_ = g;
	_tmp4_ = b;
	_tmp5_ = a;
	_tmp6_.r = _tmp2_;
	_tmp6_.g = _tmp3_;
	_tmp6_.b = _tmp4_;
	_tmp6_.a = _tmp5_;
	_tmp7_ = _entitas_tint_dup0 (&_tmp6_);
	_entitas_tint_free0 ((*self).tint);
	(*self).tint = _tmp7_;
	_tmp8_ = (*self).mask;
	(*self).mask = _tmp8_ | ENTITAS_TINT;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TintComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setTint (entitasEntity *self, gint r, gint g, gint b, gint a) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasTint* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	entitasTint* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	entitasTint* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	entitasTint* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).tint;
	_tmp3_ = r;
	(*_tmp2_).r = _tmp3_;
	_tmp4_ = (*self).tint;
	_tmp5_ = g;
	(*_tmp4_).g = _tmp5_;
	_tmp6_ = (*self).tint;
	_tmp7_ = b;
	(*_tmp6_).b = _tmp7_;
	_tmp8_ = (*self).tint;
	_tmp9_ = a;
	(*_tmp8_).a = _tmp9_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeTint (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TINT) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tint");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_tint_free0 ((*self).tint);
	(*self).tint = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TINT;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TintComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasTween (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_TWEEN) != ((guint64) 0);
	return result;
}


static gpointer _entitas_tween_dup0 (gpointer self) {
	return self ? entitas_tween_dup (self) : NULL;
}


entitasEntity* entitas_entity_addTween (entitasEntity *self, gdouble min, gdouble max, gdouble speed, gboolean repeat, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	gboolean _tmp5_ = FALSE;
	gboolean _tmp6_ = FALSE;
	entitasTween _tmp7_ = {0};
	entitasTween* _tmp8_ = NULL;
	guint64 _tmp9_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = min;
	_tmp3_ = max;
	_tmp4_ = speed;
	_tmp5_ = repeat;
	_tmp6_ = active;
	_tmp7_.min = _tmp2_;
	_tmp7_.max = _tmp3_;
	_tmp7_.speed = _tmp4_;
	_tmp7_.repeat = _tmp5_;
	_tmp7_.active = _tmp6_;
	_tmp8_ = _entitas_tween_dup0 (&_tmp7_);
	_entitas_tween_free0 ((*self).tween);
	(*self).tween = _tmp8_;
	_tmp9_ = (*self).mask;
	(*self).mask = _tmp9_ | ENTITAS_TWEEN;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_TweenComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setTween (entitasEntity *self, gdouble min, gdouble max, gdouble speed, gboolean repeat, gboolean active) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasTween* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	entitasTween* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	entitasTween* _tmp6_ = NULL;
	gdouble _tmp7_ = 0.0;
	entitasTween* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
	entitasTween* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).tween;
	_tmp3_ = min;
	(*_tmp2_).min = _tmp3_;
	_tmp4_ = (*self).tween;
	_tmp5_ = max;
	(*_tmp4_).max = _tmp5_;
	_tmp6_ = (*self).tween;
	_tmp7_ = speed;
	(*_tmp6_).speed = _tmp7_;
	_tmp8_ = (*self).tween;
	_tmp9_ = repeat;
	(*_tmp8_).repeat = _tmp9_;
	_tmp10_ = (*self).tween;
	_tmp11_ = active;
	(*_tmp10_).active = _tmp11_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeTween (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_TWEEN) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Tween");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_tween_free0 ((*self).tween);
	(*self).tween = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_TWEEN;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_TweenComponent);
	result = &(*self);
	return result;
}


gboolean entitas_entity_hasVelocity (entitasEntity *self) {
	gboolean result = FALSE;
	guint64 _tmp0_ = 0ULL;
	_tmp0_ = (*self).mask;
	result = (_tmp0_ & ENTITAS_VELOCITY) != ((guint64) 0);
	return result;
}


static gpointer _entitas_velocity_dup0 (gpointer self) {
	return self ? entitas_velocity_dup (self) : NULL;
}


entitasEntity* entitas_entity_addVelocity (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	entitasVelocity _tmp4_ = {0};
	entitasVelocity* _tmp5_ = NULL;
	guint64 _tmp6_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) != ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityAlreadyHasComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = x;
	_tmp3_ = y;
	_tmp4_.x = _tmp2_;
	_tmp4_.y = _tmp3_;
	_tmp5_ = _entitas_velocity_dup0 (&_tmp4_);
	_entitas_velocity_free0 ((*self).velocity);
	(*self).velocity = _tmp5_;
	_tmp6_ = (*self).mask;
	(*self).mask = _tmp6_ | ENTITAS_VELOCITY;
	entitas_world_onComponentAdded (&(*self), ENTITAS_COMPONENTS_VelocityComponent);
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_setVelocity (entitasEntity *self, gdouble x, gdouble y) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	entitasVelocity* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	entitasVelocity* _tmp4_ = NULL;
	gdouble _tmp5_ = 0.0;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp2_ = (*self).velocity;
	_tmp3_ = x;
	(*_tmp2_).x = _tmp3_;
	_tmp4_ = (*self).velocity;
	_tmp5_ = y;
	(*_tmp4_).y = _tmp5_;
	result = &(*self);
	return result;
}


entitasEntity* entitas_entity_removeVelocity (entitasEntity *self) {
	entitasEntity* result = NULL;
	guint64 _tmp0_ = 0ULL;
	guint64 _tmp2_ = 0ULL;
	GError * _inner_error_ = NULL;
	_tmp0_ = (*self).mask;
	if ((_tmp0_ & ENTITAS_VELOCITY) == ((guint64) 0)) {
		GError* _tmp1_ = NULL;
		_tmp1_ = g_error_new_literal (ENTITAS_EXCEPTION, ENTITAS_EXCEPTION_EntityDoesNotHaveComponent, "Velocity");
		_inner_error_ = _tmp1_;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_entitas_velocity_free0 ((*self).velocity);
	(*self).velocity = NULL;
	_tmp2_ = (*self).mask;
	(*self).mask = _tmp2_ ^ ENTITAS_VELOCITY;
	entitas_world_onComponentRemoved (&(*self), ENTITAS_COMPONENTS_VelocityComponent);
	result = &(*self);
	return result;
}


void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest) {
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	guint64 _tmp4_ = 0ULL;
	entitasBackground* _tmp5_ = NULL;
	entitasBackground* _tmp6_ = NULL;
	SDL_Rect* _tmp7_ = NULL;
	SDL_Rect* _tmp8_ = NULL;
	entitasBullet* _tmp9_ = NULL;
	entitasBullet* _tmp10_ = NULL;
	entitasEnemy1* _tmp11_ = NULL;
	entitasEnemy1* _tmp12_ = NULL;
	entitasEnemy2* _tmp13_ = NULL;
	entitasEnemy2* _tmp14_ = NULL;
	entitasEnemy3* _tmp15_ = NULL;
	entitasEnemy3* _tmp16_ = NULL;
	entitasExpires* _tmp17_ = NULL;
	entitasExpires* _tmp18_ = NULL;
	entitasHealth* _tmp19_ = NULL;
	entitasHealth* _tmp20_ = NULL;
	entitasHud* _tmp21_ = NULL;
	entitasHud* _tmp22_ = NULL;
	entitasIndex* _tmp23_ = NULL;
	entitasIndex* _tmp24_ = NULL;
	entitasLayer* _tmp25_ = NULL;
	entitasLayer* _tmp26_ = NULL;
	entitasPosition* _tmp27_ = NULL;
	entitasPosition* _tmp28_ = NULL;
	entitasScale* _tmp29_ = NULL;
	entitasScale* _tmp30_ = NULL;
	entitasSprite* _tmp31_ = NULL;
	entitasSprite* _tmp32_ = NULL;
	entitasText* _tmp33_ = NULL;
	entitasText* _tmp34_ = NULL;
	entitasTint* _tmp35_ = NULL;
	entitasTint* _tmp36_ = NULL;
	entitasTween* _tmp37_ = NULL;
	entitasTween* _tmp38_ = NULL;
	entitasVelocity* _tmp39_ = NULL;
	entitasVelocity* _tmp40_ = NULL;
	_tmp0_ = (*self).id;
	(*dest).id = _tmp0_;
	_tmp1_ = (*self).name;
	_tmp2_ = g_strdup (_tmp1_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp2_;
	_tmp3_ = (*self).pool;
	(*dest).pool = _tmp3_;
	_tmp4_ = (*self).mask;
	(*dest).mask = _tmp4_;
	_tmp5_ = (*self).background;
	_tmp6_ = _entitas_background_dup0 (_tmp5_);
	_entitas_background_free0 ((*dest).background);
	(*dest).background = _tmp6_;
	_tmp7_ = (*self).bounds;
	_tmp8_ = __sdl_video_rect_dup0 (_tmp7_);
	_g_free0 ((*dest).bounds);
	(*dest).bounds = _tmp8_;
	_tmp9_ = (*self).bullet;
	_tmp10_ = _entitas_bullet_dup0 (_tmp9_);
	_entitas_bullet_free0 ((*dest).bullet);
	(*dest).bullet = _tmp10_;
	_tmp11_ = (*self).enemy1;
	_tmp12_ = _entitas_enemy1_dup0 (_tmp11_);
	_entitas_enemy1_free0 ((*dest).enemy1);
	(*dest).enemy1 = _tmp12_;
	_tmp13_ = (*self).enemy2;
	_tmp14_ = _entitas_enemy2_dup0 (_tmp13_);
	_entitas_enemy2_free0 ((*dest).enemy2);
	(*dest).enemy2 = _tmp14_;
	_tmp15_ = (*self).enemy3;
	_tmp16_ = _entitas_enemy3_dup0 (_tmp15_);
	_entitas_enemy3_free0 ((*dest).enemy3);
	(*dest).enemy3 = _tmp16_;
	_tmp17_ = (*self).expires;
	_tmp18_ = _entitas_expires_dup0 (_tmp17_);
	_entitas_expires_free0 ((*dest).expires);
	(*dest).expires = _tmp18_;
	_tmp19_ = (*self).health;
	_tmp20_ = _entitas_health_dup0 (_tmp19_);
	_entitas_health_free0 ((*dest).health);
	(*dest).health = _tmp20_;
	_tmp21_ = (*self).hud;
	_tmp22_ = _entitas_hud_dup0 (_tmp21_);
	_entitas_hud_free0 ((*dest).hud);
	(*dest).hud = _tmp22_;
	_tmp23_ = (*self).index;
	_tmp24_ = _entitas_index_dup0 (_tmp23_);
	_entitas_index_free0 ((*dest).index);
	(*dest).index = _tmp24_;
	_tmp25_ = (*self).layer;
	_tmp26_ = _entitas_layer_dup0 (_tmp25_);
	_entitas_layer_free0 ((*dest).layer);
	(*dest).layer = _tmp26_;
	_tmp27_ = (*self).position;
	_tmp28_ = _entitas_position_dup0 (_tmp27_);
	_entitas_position_free0 ((*dest).position);
	(*dest).position = _tmp28_;
	_tmp29_ = (*self).scale;
	_tmp30_ = _entitas_scale_dup0 (_tmp29_);
	_entitas_scale_free0 ((*dest).scale);
	(*dest).scale = _tmp30_;
	_tmp31_ = (*self).sprite;
	_tmp32_ = _entitas_sprite_dup0 (_tmp31_);
	_entitas_sprite_free0 ((*dest).sprite);
	(*dest).sprite = _tmp32_;
	_tmp33_ = (*self).text;
	_tmp34_ = _entitas_text_dup0 (_tmp33_);
	_entitas_text_free0 ((*dest).text);
	(*dest).text = _tmp34_;
	_tmp35_ = (*self).tint;
	_tmp36_ = _entitas_tint_dup0 (_tmp35_);
	_entitas_tint_free0 ((*dest).tint);
	(*dest).tint = _tmp36_;
	_tmp37_ = (*self).tween;
	_tmp38_ = _entitas_tween_dup0 (_tmp37_);
	_entitas_tween_free0 ((*dest).tween);
	(*dest).tween = _tmp38_;
	_tmp39_ = (*self).velocity;
	_tmp40_ = _entitas_velocity_dup0 (_tmp39_);
	_entitas_velocity_free0 ((*dest).velocity);
	(*dest).velocity = _tmp40_;
}


void entitas_entity_destroy (entitasEntity* self) {
	_g_free0 ((*self).name);
	_entitas_background_free0 ((*self).background);
	_g_free0 ((*self).bounds);
	_entitas_bullet_free0 ((*self).bullet);
	_entitas_enemy1_free0 ((*self).enemy1);
	_entitas_enemy2_free0 ((*self).enemy2);
	_entitas_enemy3_free0 ((*self).enemy3);
	_entitas_expires_free0 ((*self).expires);
	_entitas_health_free0 ((*self).health);
	_entitas_hud_free0 ((*self).hud);
	_entitas_index_free0 ((*self).index);
	_entitas_layer_free0 ((*self).layer);
	_entitas_position_free0 ((*self).position);
	_entitas_scale_free0 ((*self).scale);
	_entitas_sprite_free0 ((*self).sprite);
	_entitas_text_free0 ((*self).text);
	_entitas_tint_free0 ((*self).tint);
	_entitas_tween_free0 ((*self).tween);
	_entitas_velocity_free0 ((*self).velocity);
}


entitasEntity* entitas_entity_dup (const entitasEntity* self) {
	entitasEntity* dup;
	dup = g_new0 (entitasEntity, 1);
	entitas_entity_copy (self, dup);
	return dup;
}


void entitas_entity_free (entitasEntity* self) {
	entitas_entity_destroy (self);
	g_free (self);
}


GType entitas_entity_get_type (void) {
	static volatile gsize entitas_entity_type_id__volatile = 0;
	if (g_once_init_enter (&entitas_entity_type_id__volatile)) {
		GType entitas_entity_type_id;
		entitas_entity_type_id = g_boxed_type_register_static ("entitasEntity", (GBoxedCopyFunc) entitas_entity_dup, (GBoxedFreeFunc) entitas_entity_free);
		g_once_init_leave (&entitas_entity_type_id__volatile, entitas_entity_type_id);
	}
	return entitas_entity_type_id__volatile;
}



